### ISSUE TITLE
SQLITE_IOERR_WRITE

### ISSUE THREAD

**Issue by soshimee** [PlayPro/CoreProtect#103]
```
[14:19:32 WARN]: org.sqlite.SQLiteException: [SQLITE_IOERR_WRITE]  I/O error in the VFS layer while trying to write to a file on disk (disk I/O error)
[14:19:32 WARN]:     at org.sqlite.core.DB.newSQLException(DB.java:1012)
[14:19:32 WARN]:     at org.sqlite.core.DB.newSQLException(DB.java:1024)
[14:19:32 WARN]:     at org.sqlite.core.DB.throwex(DB.java:989)
[14:19:32 WARN]:     at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[14:19:32 WARN]:     at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
[14:19:32 WARN]:     at org.sqlite.core.DB.prepare(DB.java:257)
[14:19:32 WARN]:     at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
[14:19:32 WARN]:     at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
[14:19:32 WARN]:     at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
[14:19:32 WARN]:     at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
[14:19:32 WARN]:     at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
[14:19:32 WARN]:     at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
[14:19:32 WARN]:     at net.coreprotect.database.Database.prepareStatement(Database.java:282)
[14:19:32 WARN]:     at net.coreprotect.database.Database.prepareStatement(Database.java:228)
[14:19:32 WARN]:     at net.coreprotect.consumer.process.Process.processConsumer(Process.java:125)
[14:19:32 WARN]:     at net.coreprotect.consumer.Consumer.run(Consumer.java:141)
[14:19:32 WARN]:     at java.base/java.lang.Thread.run(Thread.java:829)
```
This warning spams my console and database is always busy.

**Comment by Intelli** [comment]
https://www.sqlite.org/rescode.html#ioerr_write
