### ISSUE TITLE
Problem with MySQL

### ISSUE THREAD

**Issue by LeftTheNegotiator** [PlayPro/CoreProtect#105]
Hello, I get this when running my server for a while:

`[19:44:03 INFO]: [CoreProtect] Unable to connect to MySQL server.
[19:44:03 WARN]: java.sql.SQLException: No suitable driver found for jdbc:mysql://s1.earthcraft.heavynode.net:3306/s1_mysql?useUnicode=true&characterEncoding=utf-8&connectTimeout=10000&useSSL=false&allowPublicKeyRetrieval=true&useCursorFetch=true&useLocalSessionState=true&rewriteBatchedStatements=true&maintainTimeStats=false
[19:44:03 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
[19:44:03 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
[19:44:03 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.database.Database.getConnection(Database.java:143)
[19:44:03 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.database.Database.getConnection(Database.java:130)
[19:44:03 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.consumer.process.Process.validateConnection(Process.java:69)
[19:44:03 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:95)
[19:44:03 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:141)
[19:44:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)`

**Comment by vacla** [comment]
@LeftTheNegotiator are you using Plan? If not can you share your plugin list?
