### ISSUE TITLE
Unknown column 'data' in 'field list' Warning

### ISSUE THREAD

**Issue by Maxence621** [PlayPro/CoreProtect#110]
Hello, so as my title say, i have this error/warning, the thing is it's a warning so it's kind of okay, but it have a lot of lines
and it spam a little bit sometimes so.. i wonder how to fix this warning since i didn't have it before ?
Thank you for answering !

The Error/Warning :
[19:47:01 WARN]: java.sql.BatchUpdateException: Unknown column 'data' in 'field list'
[19:47:01 WARN]:        at jdk.internal.reflect.GeneratedConstructorAccessor227.newInstance(Unknown Source)
[19:47:01 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:47:01 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[19:47:01 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[19:47:01 WARN]:        at com.mysql.cj.util.Util.handleNewInstance(Util.java:192)
[19:47:01 WARN]:        at com.mysql.cj.util.Util.getInstance(Util.java:167)
[19:47:01 WARN]:        at com.mysql.cj.util.Util.getInstance(Util.java:174)
[19:47:01 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224)
[19:47:01 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchedInserts(ClientPreparedStatement.java:755)
[19:47:01 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:426)
[19:47:01 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:794)
[19:47:01 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.consumer.process.Process.commit(Process.java:307)
[19:47:01 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:268)
[19:47:01 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:141)
[19:47:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[19:47:01 WARN]: Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'data' in 'field list'
[19:47:01 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[19:47:01 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[19:47:01 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[19:47:01 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
[19:47:01 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
[19:47:01 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
[19:47:01 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchedInserts(ClientPreparedStatement.java:716)
[19:47:01 WARN]:        ... 6 more
[19:47:04 WARN]: java.sql.BatchUpdateException: Unknown column 'data' in 'field list'
[19:47:04 WARN]:        at jdk.internal.reflect.GeneratedConstructorAccessor227.newInstance(Unknown Source)
[19:47:04 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:47:04 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[19:47:04 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[19:47:04 WARN]:        at com.mysql.cj.util.Util.handleNewInstance(Util.java:192)
[19:47:04 WARN]:        at com.mysql.cj.util.Util.getInstance(Util.java:167)
[19:47:04 WARN]:        at com.mysql.cj.util.Util.getInstance(Util.java:174)
[19:47:04 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224)
[19:47:04 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchedInserts(ClientPreparedStatement.java:755)
[19:47:04 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:426)
[19:47:04 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:794)
[19:47:04 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.consumer.process.Process.commit(Process.java:307)
[19:47:04 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:268)
[19:47:04 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:141)
[19:47:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[19:47:04 WARN]: Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'data' in 'field list'
[19:47:04 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[19:47:04 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[19:47:04 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[19:47:04 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
[19:47:04 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
[19:47:04 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
[19:47:04 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchedInserts(ClientPreparedStatement.java:716)
[19:47:04 WARN]:        ... 6 more
[19:47:14 WARN]: java.sql.BatchUpdateException: Unknown column 'data' in 'field list'
[19:47:14 WARN]:        at jdk.internal.reflect.GeneratedConstructorAccessor227.newInstance(Unknown Source)
[19:47:14 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:47:14 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[19:47:14 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[19:47:14 WARN]:        at com.mysql.cj.util.Util.handleNewInstance(Util.java:192)
[19:47:14 WARN]:        at com.mysql.cj.util.Util.getInstance(Util.java:167)
[19:47:14 WARN]:        at com.mysql.cj.util.Util.getInstance(Util.java:174)
[19:47:14 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224)
[19:47:14 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchedInserts(ClientPreparedStatement.java:755)
[19:47:14 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:426)
[19:47:14 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:794)
[19:47:14 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.consumer.process.Process.commit(Process.java:307)
[19:47:14 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:268)
[19:47:14 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:141)
[19:47:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[19:47:14 WARN]: Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'data' in 'field list'
[19:47:14 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[19:47:14 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[19:47:14 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[19:47:14 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
[19:47:14 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
[19:47:14 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
[19:47:14 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchedInserts(ClientPreparedStatement.java:716)
[19:47:14 WARN]:        ... 6 more

**Comment by Intelli** [comment]
Sounds like one of your tables is missing a column named `data`. Did you make any recent changes to your server?

**Comment by Maxence621** [comment]
> Sounds like one of your tables is missing a column named `data`. Did you make any recent changes to your server?

I did a lot of changes these days, should i do something to fix it ? (i'm okay to reset all the database, since nobody grief anything in my worlds)

**Comment by vacla** [comment]
It would be the easiest way

**Comment by Maxence621** [comment]
> It would be the easiest way to reset and would fix it directly

how can i do that? should i just drop the database table and remove it?

**Comment by Intelli** [comment]
Dropping the tables would work.
