### ISSUE TITLE
Error when handling items with lots of NBT

### ISSUE THREAD

**Issue by kruthers** [PlayPro/CoreProtect#111]
On the server we have a couple of items with a lot of NBT attached to them, the error below is caused from taking a book that has almost 300 pages. As this is a book that can only be gained using commands and as a book this big can not normal be made in vanilla, i dont expect it to be stored, but it would be nice for the error message to be hidden or logged somewhere else to provent it clogging up the logs.

Error:
```
java.sql.BatchUpdateException: Data truncation: Data too long for column 'metadata' at row 1
[16:51:03 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[16:51:03 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[16:51:03 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[16:51:03 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[16:51:03 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[16:51:03 WARN]:        at com.mysql.cj.util.Util.handleNewInstance(Util.java:192)
[16:51:03 WARN]:        at com.mysql.cj.util.Util.getInstance(Util.java:167)
[16:51:03 WARN]:        at com.mysql.cj.util.Util.getInstance(Util.java:174)
[16:51:03 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224)
[16:51:03 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchedInserts(ClientPreparedStatement.java:755)
[16:51:03 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:426)
[16:51:03 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:794)
[16:51:03 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.consumer.process.Process.commit(Process.java:310)
[16:51:03 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:268)
[16:51:03 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:141)
[16:51:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[16:51:03 WARN]: Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'metadata' at row 1
[16:51:03 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
[16:51:03 WARN]:        at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:637)
[16:51:03 WARN]:        at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:418)
[16:51:03 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
[16:51:03 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
[16:51:03 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
[16:51:03 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchedInserts(ClientPreparedStatement.java:716)
[16:51:03 WARN]:        ... 6 more
```

**Comment by Intelli** [comment]
Can you provide steps to replicate?
