### ISSUE TITLE
Cant inspect chest inventory

### ISSUE THREAD

**Issue by PenguinAlex** [PlayPro/CoreProtect#115]
[08:56:38] [Server thread/INFO]: [STDOUT]: Negative index in crash report handler (0/21)
[08:56:38] [Server thread/FATAL]: Error executing task on Server
net.minecraft.class_148: Sending packet
        at net.minecraft.class_3244.method_14369(class_3244.java:1165) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.class_3244.method_14364(class_3244.java:1153) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.class_3225.handler$zec000$processBlockBreakingActionBF(class_3225.java:618) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.class_3225.method_14263(class_3225.java) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.class_3244.method_12066(class_3244.java:1018) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.class_2846.method_12361(class_2846.java:34) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.class_2846.method_11054(class_2846.java:8) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:741) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server-1.18.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException
[08:56:41] [Server thread/WARN]: Mismatch in destroy block pos: class_2338{x=-579, y=75, z=66} class_2338{x=-584, y=75, z=63}
[08:56:41] [Server thread/WARN]: Mismatch in destroy block pos: class_2338{x=-579, y=75, z=66} class_2338{x=-584, y=75, z=68}

**Comment by Intelli** [comment]
Not a CoreProtect error.

**Comment by vacla** [comment]
@PenguinAlex from the looks you are running Fabric, CoreProtect plugin is not supported on Fabric.
