### ISSUE TITLE
Paper Server 1.17.1: Incompatibility of CoreProtect 20.1 with Gringotts 2.12.2

### ISSUE THREAD

**Issue by silen72** [PlayPro/CoreProtect#117]
I have a server (Paper, MC:1.16.5) with quite a few plugin. CoreProtect (19.5) is configured to use a MySQL database (version 8.0.22). One of the other plugins is Gringotts v2.12.2. This works well.

Currently I'm trying to upgrade my server to Paper, MC:1.17.1 (git-Paper-399). For this, I have also upgraded CoreProtect (to 20.1) - Gringotts is already the current version. I have also switched to Java 17 (OpenJDK 64-Bit Server VM 17.0.1+12-39). With this configuration, CoreProtect fails to connect to the database:

[20:52:55 INFO]: [CoreProtect] Unable to connect to MySQL server.
[20:52:55 WARN]: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/minecraft?useUnicode=true&characterEncoding=utf-8&connectTimeout=10000&useSSL=false&allowPublicKeyRetrieval=true&useCursorFetch=true&useLocalSessionState=true&rewriteBatchedStatements=true&maintainTimeStats=false
[20:52:55 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:706)
[20:52:55 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
[20:52:55 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.database.Database.getConnection(Database.java:143)
[20:52:55 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.database.Database.createDatabaseTables(Database.java:320)
[20:52:55 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.config.ConfigHandler.loadDatabase(ConfigHandler.java:205)
[20:52:55 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:367)
[20:52:55 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.CoreProtect.onEnable(CoreProtect.java:71)
[20:52:55 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[20:52:55 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[20:52:55 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[20:52:55 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[20:52:55 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[20:52:55 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733)
[20:52:55 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[20:52:55 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
[20:52:55 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[20:52:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

For troubleshooting I have disabled all plugins **but** CoreProtect. After a restart, CoreProtect was back to normal; it successfully connected to my MySQL server. I have then reenabled one plugin after another. What I found out is, that as soon as I have Gringotts and CoreProtect both active, CoreProtect fails to connect.

I do not know if this is rather an issue with CoreProtect or with Gringotts, so I decided to file an issue with both plugins.

This might also be related to #105 although that issue does not contain much additional information besides the error message.
I have filed this issue with Gringotts here: https://github.com/nikosgram/gringotts/issues/82.

Maybe this is valuable info: when shutting down the server, there are warnings caused by gingotts that also seem database related:

[20:55:45 INFO]: Closing Server
[20:55:52 WARN]: java.lang.IllegalStateException: zip file closed
[20:55:52 WARN]:        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
[20:55:52 WARN]:        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
[20:55:52 WARN]:        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
[20:55:52 WARN]:        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
[20:55:52 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163)
[20:55:52 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[20:55:52 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[20:55:52 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[20:55:52 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[20:55:52 WARN]:        at gringotts-2.12.2.jar//com.avaje.ebeaninternal.server.lib.sql.PooledConnectionQueue.createStatus(PooledConnectionQueue.java:125)
[20:55:52 WARN]:        at gringotts-2.12.2.jar//com.avaje.ebeaninternal.server.lib.sql.PooledConnectionQueue.shutdown(PooledConnectionQueue.java:354)
[20:55:52 WARN]:        at gringotts-2.12.2.jar//com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.shutdown(DataSourcePool.java:689)
[20:55:52 WARN]:        at gringotts-2.12.2.jar//com.avaje.ebeaninternal.server.lib.sql.DataSourceManager.shutdown(DataSourceManager.java:170)

**Comment by Intelli** [comment]
#105 was due to the plugin “Plan” unregistering the MySQL driver. Gringotts may be doing something similar, which they would need to fix.

**Comment by silen72** [comment]
Thanks @Intelli for looking into this - @nikosgram over at gringotts showed no reaction so far. Shall I keep this issue updated with things happening over there (and vice versa)?

**Comment by Intelli** [comment]
Sure. The information here may also be of use: https://github.com/plan-player-analytics/Plan/issues/2147

**Comment by silen72** [comment]
No updates on my issue over at Gringotts so far...

I've tinkered a bit with the source code of my own plugin as well as with Gringotts. Gringotts does not unregister the MySQL driver, at least I did not find anything obvious like `DriverManager.deregisterDriver(...)`. It uses a (fairly outdated?) version of ebean (2.8.1) with SQLite. I did not investigate any deeper into that - so ebean _may_ be unregistering the MySQL driver.

But I was able to fix my plugin - I simply (re-)added `Class.forName("com.mysql.cj.jdbc.Driver");` before trying to connect to the database - that did the trick. Maybe you want to (re-)add that statement to CoreProtext too (which was there in version 19.5 presumably)?

For now I have hacked that statement in a local fork into Gringotts' onLoad method - that (temporarily?) fixes the issue with CoreProtect. It surely does NOT belong there because Gringotts does not use MySQL at all...

**Comment by brayjamin** [comment]
The same issue is prevalent when using [grakkit](https://github.com/grakkit/grakkit) with CoreProtect, in 1.18. ([relevant Grakkit )issue](https://github.com/grakkit/grakkit/issues/14)

It seems to work in 1.17, now, perhaps a patch removed this (again again)!

**Comment by silen72** [comment]
Thanks a lot, @Intelli!
