### ISSUE TITLE
Mysql Error

### ISSUE THREAD

**Issue by BautistaIza** [PlayPro/CoreProtect#124]
**Problem with MYSQL when starting the server (1.17.1)**

[22:33:52 INFO]: [CoreProtect] Enabling CoreProtect v20.3
[22:33:53 INFO]: [net.coreprotect.hikari.HikariDataSource] HikariPool-1 - Starting...
[22:33:54 ERROR]: [net.coreprotect.hikari.pool.HikariPool] HikariPool-1 - Exception during pool initialization.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[patched_1.17.1.jar:git-Paper-402]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[patched_1.17.1.jar:git-Paper-402]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833) ~[patched_1.17.1.jar:git-Paper-402]
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[patched_1.17.1.jar:git-Paper-402]
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[patched_1.17.1.jar:git-Paper-402]
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[patched_1.17.1.jar:git-Paper-402]
        at net.coreprotect.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[CoreProtect.jar:?]
        at net.coreprotect.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[CoreProtect.jar:?]
        at net.coreprotect.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[CoreProtect.jar:?]
        at net.coreprotect.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[CoreProtect.jar:?]
        at net.coreprotect.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[CoreProtect.jar:?]
        at net.coreprotect.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[CoreProtect.jar:?]
        at net.coreprotect.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[CoreProtect.jar:?]
        at net.coreprotect.config.ConfigHandler.loadDatabase(ConfigHandler.java:232) ~[CoreProtect.jar:?]
        at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:398) ~[CoreProtect.jar:?]
        at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:71) ~[CoreProtect.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-402]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-402]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-402]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-402]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-402]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-402]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-402]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-402]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-402]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[patched_1.17.1.jar:git-Paper-402]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[patched_1.17.1.jar:git-Paper-402]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[patched_1.17.1.jar:git-Paper-402]
        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[patched_1.17.1.jar:git-Paper-402]
        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89) ~[patched_1.17.1.jar:git-Paper-402]
        at com.mysql.cj.NativeSession.connect(NativeSession.java:144) ~[patched_1.17.1.jar:git-Paper-402]
        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953) ~[patched_1.17.1.jar:git-Paper-402]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823) ~[patched_1.17.1.jar:git-Paper-402]
        ... 23 more
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
        at sun.nio.ch.Net.pollConnectNow(Net.java:669) ~[?:?]
        at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) ~[?:?]
        at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333) ~[?:?]
        at java.net.Socket.connect(Socket.java:645) ~[?:?]
        at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155) ~[patched_1.17.1.jar:git-Paper-402]
        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63) ~[patched_1.17.1.jar:git-Paper-402]
        at com.mysql.cj.NativeSession.connect(NativeSession.java:144) ~[patched_1.17.1.jar:git-Paper-402]
        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953) ~[patched_1.17.1.jar:git-Paper-402]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823) ~[patched_1.17.1.jar:git-Paper-402]
        ... 23 more
[22:33:54 WARN]: net.coreprotect.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure
[22:33:54 WARN]:        at CoreProtect.jar//net.coreprotect.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
[22:33:54 WARN]:        at CoreProtect.jar//net.coreprotect.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
[22:33:54 WARN]:        at CoreProtect.jar//net.coreprotect.hikari.pool.HikariPool.<init>(HikariPool.java:115)
[22:33:54 WARN]:        at CoreProtect.jar//net.coreprotect.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
[22:33:54 WARN]:        at CoreProtect.jar//net.coreprotect.config.ConfigHandler.loadDatabase(ConfigHandler.java:232)
[22:33:54 WARN]:        at CoreProtect.jar//net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:398)
[22:33:54 WARN]:        at CoreProtect.jar//net.coreprotect.CoreProtect.onEnable(CoreProtect.java:71)
[22:33:54 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[22:33:54 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[22:33:54 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[22:33:54 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[22:33:54 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[22:33:54 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733)
[22:33:54 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[22:33:54 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
[22:33:54 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[22:33:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[22:33:54 WARN]: Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
[22:33:54 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
[22:33:54 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[22:33:54 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833)
[22:33:54 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)
[22:33:54 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
[22:33:54 WARN]:        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[22:33:54 WARN]:        at CoreProtect.jar//net.coreprotect.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
[22:33:54 WARN]:        at CoreProtect.jar//net.coreprotect.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
[22:33:54 WARN]:        at CoreProtect.jar//net.coreprotect.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
[22:33:54 WARN]:        at CoreProtect.jar//net.coreprotect.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
[22:33:54 WARN]:        at CoreProtect.jar//net.coreprotect.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
[22:33:54 WARN]:        ... 15 more
[22:33:54 WARN]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
[22:33:54 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[22:33:54 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[22:33:54 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[22:33:54 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[22:33:54 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[22:33:54 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[22:33:54 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[22:33:54 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[22:33:54 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
[22:33:54 WARN]:        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
[22:33:54 WARN]:        at com.mysql.cj.NativeSession.connect(NativeSession.java:144)
[22:33:54 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953)
[22:33:54 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
[22:33:54 WARN]:        ... 23 more
[22:33:54 WARN]: Caused by: java.net.ConnectException: Connection refused
[22:33:54 WARN]:        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[22:33:54 WARN]:        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:669)
[22:33:54 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
[22:33:54 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
[22:33:54 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
[22:33:54 WARN]:        at java.base/java.net.Socket.connect(Socket.java:645)
[22:33:54 WARN]:        at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
[22:33:54 WARN]:        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
[22:33:54 WARN]:        ... 26 more
[22:33:54 INFO]: [CoreProtect] Incapaz de conectarse a MySQL servidor.
[22:33:54 WARN]: java.lang.NullPointerException: Cannot invoke "net.coreprotect.hikari.HikariDataSource.getConnection()" because "net.coreprotect.config.ConfigHandler.hikariDataSource" is null
[22:33:54 WARN]:        at CoreProtect.jar//net.coreprotect.database.Database.getConnection(Database.java:141)
[22:33:54 WARN]:        at CoreProtect.jar//net.coreprotect.database.Database.getConnection(Database.java:130)
[22:33:54 WARN]:        at CoreProtect.jar//net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:405)
[22:33:54 WARN]:        at CoreProtect.jar//net.coreprotect.CoreProtect.onEnable(CoreProtect.java:71)
[22:33:54 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[22:33:54 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[22:33:54 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[22:33:54 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[22:33:54 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[22:33:54 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733)
[22:33:54 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[22:33:54 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
[22:33:54 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[22:33:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[22:33:54 WARN]: java.lang.NullPointerException: Cannot invoke "java.sql.Connection.createStatement()" because "connection" is null
[22:33:54 WARN]:        at CoreProtect.jar//net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:406)
[22:33:54 WARN]:        at CoreProtect.jar//net.coreprotect.CoreProtect.onEnable(CoreProtect.java:71)
[22:33:54 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[22:33:54 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[22:33:54 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[22:33:54 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[22:33:54 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[22:33:54 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733)
[22:33:54 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[22:33:54 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
[22:33:54 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[22:33:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[22:33:54 INFO]: [CoreProtect] CoreProtect fue incapaz de comenzar.
[22:33:54 INFO]: [CoreProtect] Disabling CoreProtect v20.3
[22:33:54 INFO]: [CoreProtect] Terminando el registro de datos. Espere por favor...
[22:33:54 INFO]: [CoreProtect] ¡Éxito! Discapacitado CoreProtect v20.3

**Comment by Intelli** [comment]
> Failed to initialize pool: Communications link failure

Doesn’t appear to be an issue with CoreProtect.
