### ISSUE TITLE
SQL error or missing database (no such table: co_block)

### ISSUE THREAD

**Issue by TimSauter** [PlayPro/CoreProtect#143]
HI there,
I'm using Spigot 1.18.1 MC-Server and just copied the CoreProtect-20.4.jar in the plugin folder but unfurtunately the plugin isn't working completly. I always get an error when typing "/co inspect" and click on any block.
I didn't find any configuration files for the plugin and the database.db is in the folder .../plugins/CoreProtect where it should be.

[Sun, 30. Jan 2022 17:55:36 UTC WARN] org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: co_block)
[Sun, 30. Jan 2022 17:55:36 UTC WARN] at org.sqlite.core.DB.newSQLException(DB.java:1030)
[Sun, 30. Jan 2022 17:55:36 UTC WARN] at org.sqlite.core.DB.newSQLException(DB.java:1042)
[Sun, 30. Jan 2022 17:55:36 UTC WARN] at org.sqlite.core.DB.throwex(DB.java:1007)
[Sun, 30. Jan 2022 17:55:36 UTC WARN] at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[Sun, 30. Jan 2022 17:55:36 UTC WARN] at org.sqlite.core.NativeDB.prepare(NativeDB.java:137)
[Sun, 30. Jan 2022 17:55:36 UTC WARN] at org.sqlite.core.DB.prepare(DB.java:257)
[Sun, 30. Jan 2022 17:55:36 UTC WARN] at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:66)
[Sun, 30. Jan 2022 17:55:36 UTC WARN] at net.coreprotect.database.lookup.BlockLookup.performLookup(BlockLookup.java:60)
[Sun, 30. Jan 2022 17:55:36 UTC WARN] at net.coreprotect.listener.player.PlayerInteractListener$1BasicThread.run(PlayerInteractListener.java:111)
[Sun, 30. Jan 2022 17:55:36 UTC WARN] at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by TimSauter** [comment]
I fixed it myself. I missed the file libawt_xawt.so in /usr/lib/jvm/java-17-openjdk-amd64/lib/ because I had only openjdk-17-jre-headless installed. After installing openjdk-17-jre and reinstalling (deleting CoreProtect plugin folder and restarting server) the plugin everything is working fine.
