### ISSUE TITLE
db file was broken.

### ISSUE THREAD

**Issue by NCSV** [PlayPro/CoreProtect#147]
purpur  1.18.1 RO.1
coreprotect 20.3

[05:02:16] [Thread-16/WARN]: org.sqlite.SQLiteException: [SQLITE_IOERR_WRITE]  I/O error in the VFS layer while trying to write to a file on disk (disk I/O error)
[05:02:16] [Thread-16/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1030)
[05:02:16] [Thread-16/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1042)
[05:02:16] [Thread-16/WARN]: 	at org.sqlite.core.DB.throwex(DB.java:1007)
[05:02:16] [Thread-16/WARN]: 	at org.sqlite.core.NativeDB._exec_utf8(Native Method)
[05:02:16] [Thread-16/WARN]: 	at org.sqlite.core.NativeDB._exec(NativeDB.java:97)
[05:02:16] [Thread-16/WARN]: 	at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:102)
[05:02:16] [Thread-16/WARN]: 	at CoreProtect-20.3.jar//net.coreprotect.database.Database.commitTransaction(Database.java:70)
[05:02:16] [Thread-16/WARN]: 	at CoreProtect-20.3.jar//net.coreprotect.consumer.process.Process.commit(Process.java:290)
[05:02:16] [Thread-16/WARN]: 	at CoreProtect-20.3.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:242)
[05:02:16] [Thread-16/WARN]: 	at CoreProtect-20.3.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[05:02:16] [Thread-16/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Intelli** [comment]
https://www.sqlite.org/rescode.html#ioerr_write

Your `database.db` file could be corrupted. Try deleting the file and restarting your server.

**Comment by soshimee** [comment]
I have this issue as well, it keeps corrupting every few days.
