### ISSUE TITLE
Server Crash: Could not pass event ProjectileLaunchEvent to CoreProtect v21.0

### ISSUE THREAD

**Issue by nsgwick** [PlayPro/CoreProtect#174]
I haven't yet updated but since I've seen the changelog  for 21.1 this wasn't mentioned. My server just crashed because of this:
`[11:02:33] [Server thread/ERROR]: Could not pass event ProjectileLaunchEvent to CoreProtect v21.0
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getName()" because "player" is null
	at net.coreprotect.listener.player.ProjectileLaunchListener.onProjectileLaunch(ProjectileLaunchListener.java:98) ~[CoreProtect-21.0.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-235]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callProjectileLaunchEvent(CraftEventFactory.java:1398) ~[paper-1.18.2.jar:git-Paper-235]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:649) ~[paper-1.18.2.jar:git-Paper-235]
	at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1419) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1331) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1326) ~[?:?]
	at net.minecraft.world.item.BowItem.releaseUsing(BowItem.java:85) ~[?:?]
	at net.minecraft.world.item.ItemStack.releaseUsing(ItemStack.java:744) ~[paper-1.18.2.jar:git-Paper-235]
	at net.minecraft.world.entity.LivingEntity.releaseUsingItem(LivingEntity.java:3863) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1751) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:8) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-235]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1401) ~[paper-1.18.2.jar:git-Paper-235]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[paper-1.18.2.jar:git-Paper-235]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1378) ~[paper-1.18.2.jar:git-Paper-235]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1371) ~[paper-1.18.2.jar:git-Paper-235]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1506) ~[paper-1.18.2.jar:git-Paper-235]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1227) ~[paper-1.18.2.jar:git-Paper-235]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-235]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

**Comment by Intelli** [comment]
Fixed in https://github.com/PlayPro/CoreProtect/commit/01ed2e9f973084d4a919a4ca01da51642a1346d0
