### ISSUE TITLE
java.io.NotSerializableException: org.bukkit.potion.PotionEffect in paper 1.14.4

### ISSUE THREAD

**Issue by In77** [PlayPro/CoreProtect#19]
<img width="491" alt="Screenshot 2019-09-15 at 17 36 15" src="https://user-images.githubusercontent.com/44344308/64919596-7ad57880-d7df-11e9-85d5-022ce9b7e915.png">

[17:29:43 WARN]: java.io.NotSerializableException: org.bukkit.potion.PotionEffect
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.j
ava:1184)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
[17:29:43 WARN]:        at java.util.ArrayList.writeObject(ArrayList.java:766)
[17:29:43 WARN]:        at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
[17:29:43 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:29:43 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[17:29:43 WARN]:        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
[17:29:43 WARN]:        at java.util.ArrayList.writeObject(ArrayList.java:766)
[17:29:43 WARN]:        at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
[17:29:43 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:29:43 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[17:29:43 WARN]:        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
[17:29:43 WARN]:        at net.coreprotect.Functions.convertByteData(Functions.java:372)
[17:29:43 WARN]:        at net.coreprotect.database.Database.insertContainer(Database.java:281)
[17:29:43 WARN]:        at net.coreprotect.database.Logger.container_logger(Logger.java:195)
[17:29:43 WARN]:        at net.coreprotect.database.Logger.log_container(Logger.java:360)
[17:29:43 WARN]:        at net.coreprotect.consumer.Process.processContainerTransaction(Process.java:324)
[17:29:43 WARN]:        at net.coreprotect.consumer.Process.processConsumer(Process.java:153)
[17:29:43 WARN]:        at net.coreprotect.consumer.Consumer.run(Consumer.java:124)
[17:29:43 WARN]:        at java.lang.Thread.run(Thread.java:748)
[17:29:43 WARN]: java.io.NotSerializableException: org.bukkit.potion.PotionEffect
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
[17:29:43 WARN]:        at java.util.ArrayList.writeObject(ArrayList.java:766)
[17:29:43 WARN]:        at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
[17:29:43 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:29:43 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[17:29:43 WARN]:        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
[17:29:43 WARN]:        at java.util.ArrayList.writeObject(ArrayList.java:766)
[17:29:43 WARN]:        at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
[17:29:43 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:29:43 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[17:29:43 WARN]:        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[17:29:43 WARN]:        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
[17:29:43 WARN]:        at net.coreprotect.Functions.convertByteData(Functions.java:372)
[17:29:43 WARN]:        at net.coreprotect.database.Database.insertContainer(Database.java:281)
[17:29:43 WARN]:        at net.coreprotect.database.Logger.container_logger(Logger.java:195)
[17:29:43 WARN]:        at net.coreprotect.database.Logger.log_container(Logger.java:360)
[17:29:43 WARN]:        at net.coreprotect.consumer.Process.processContainerTransaction(Process.java:324)
[17:29:43 WARN]:        at net.coreprotect.consumer.Process.processConsumer(Process.java:153)
[17:29:43 WARN]:        at net.coreprotect.consumer.Consumer.run(Consumer.java:124)
[17:29:43 WARN]:        at java.lang.Thread.run(Thread.java:748)
[17:29:49 WARN]: java.io.NotSerializableException: org.bukkit.potion.PotionEffect
[17:29:49 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
[17:29:49 WARN]:        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
[17:29:49 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
[17:29:49 WARN]:        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
[17:29:49 WARN]:        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
[17:29:49 WARN]:        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[17:29:49 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[17:29:49 WARN]:        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
[17:29:49 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
[17:29:49 WARN]:        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
[17:29:49 WARN]:        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
[17:29:49 WARN]:        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[17:29:49 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[17:29:49 WARN]:        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
[17:29:49 WARN]:        at java.util.ArrayList.writeObject(ArrayList.java:766)
[17:29:49 WARN]:        at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
[17:29:49 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:29:49 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[17:29:49 WARN]:        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
[17:29:49 WARN]:        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
[17:29:49 WARN]:        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[17:29:49 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[17:29:49 WARN]:        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
[17:29:49 WARN]:        at java.util.ArrayList.writeObject(ArrayList.java:766)
[17:29:49 WARN]:        at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
[17:29:49 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:29:49 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[17:29:49 WARN]:        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
[17:29:49 WARN]:        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
[17:29:49 WARN]:        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[17:29:49 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[17:29:49 WARN]:        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
[17:29:49 WARN]:        at net.coreprotect.Functions.convertByteData(Functions.java:372)
[17:29:49 WARN]:        at net.coreprotect.database.Database.insertContainer(Database.java:281)
[17:29:49 WARN]:        at net.coreprotect.database.Logger.container_logger(Logger.java:195)
[17:29:49 WARN]:        at net.coreprotect.database.Logger.log_container(Logger.java:361)
[17:29:49 WARN]:        at net.coreprotect.consumer.Process.processContainerTransaction(Process.java:324)
[17:29:49 WARN]:        at net.coreprotect.consumer.Process.processConsumer(Process.java:153)
[17:29:49 WARN]:        at net.coreprotect.consumer.Consumer.run(Consumer.java:124)
[17:29:49 WARN]:        at java.lang.Thread.run(Thread.java:748)
[17:29:54 WARN]: java.io.NotSerializableException: org.bukkit.potion.PotionEffect
[17:29:54 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
[17:29:54 WARN]:        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
[17:29:54 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
[17:29:54 WARN]:        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
[17:29:54 WARN]:        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
[17:29:54 WARN]:        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[17:29:54 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[17:29:54 WARN]:        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
[17:29:54 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
[17:29:54 WARN]:        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
[17:29:54 WARN]:        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
[17:29:54 WARN]:        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[17:29:54 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[17:29:54 WARN]:        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
[17:29:54 WARN]:        at java.util.ArrayList.writeObject(ArrayList.java:766)
[17:29:54 WARN]:        at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
[17:29:54 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:29:54 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[17:29:54 WARN]:        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
[17:29:54 WARN]:        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
[17:29:54 WARN]:        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[17:29:54 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[17:29:54 WARN]:        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
[17:29:54 WARN]:        at java.util.ArrayList.writeObject(ArrayList.java:766)
[17:29:54 WARN]:        at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
[17:29:54 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:29:54 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[17:29:54 WARN]:        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
[17:29:54 WARN]:        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
[17:29:54 WARN]:        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[17:29:54 WARN]:        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[17:29:54 WARN]:        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
[17:29:54 WARN]:        at net.coreprotect.Functions.convertByteData(Functions.java:372)
[17:29:54 WARN]:        at net.coreprotect.database.Database.insertContainer(Database.java:281)
[17:29:54 WARN]:        at net.coreprotect.database.Logger.container_logger(Logger.java:195)
[17:29:54 WARN]:        at net.coreprotect.database.Logger.log_container(Logger.java:361)
[17:29:54 WARN]:        at net.coreprotect.consumer.Process.processContainerTransaction(Process.java:324)
[17:29:54 WARN]:        at net.coreprotect.consumer.Process.processConsumer(Process.java:153)
[17:29:54 WARN]:        at net.coreprotect.consumer.Consumer.run(Consumer.java:124)
[17:29:54 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by crizyx** [comment]
Same error on paper 1.14 build 192.

```java
[12:26:03 WARN]: java.io.NotSerializableException: org.bukkit.potion.PotionEffect
>.... [12:26:03 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
>.... [12:26:03 WARN]: at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
>.... [12:26:03 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
>.... [12:26:03 WARN]: at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
>.... [12:26:03 WARN]: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
>.... [12:26:03 WARN]: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
>.... [12:26:03 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
>.... [12:26:03 WARN]: at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
>.... [12:26:03 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
>.... [12:26:03 WARN]: at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
>.... [12:26:03 WARN]: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
>.... [12:26:03 WARN]: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
>.... [12:26:03 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
>.... [12:26:03 WARN]: at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
>.... [12:26:03 WARN]: at java.util.ArrayList.writeObject(ArrayList.java:766)
>.... [12:26:03 WARN]: at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
>.... [12:26:03 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [12:26:03 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [12:26:03 WARN]: at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
>.... [12:26:03 WARN]: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
>.... [12:26:03 WARN]: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
>.... [12:26:03 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
>.... [12:26:03 WARN]: at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
>.... [12:26:03 WARN]: at java.util.ArrayList.writeObject(ArrayList.java:766)
>.... [12:26:03 WARN]: at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
>.... [12:26:03 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [12:26:03 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [12:26:03 WARN]: at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
>.... [12:26:03 WARN]: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
>.... [12:26:03 WARN]: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
>.... [12:26:03 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
>.... [12:26:03 WARN]: at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
>.... [12:26:03 WARN]: at net.coreprotect.Functions.convertByteData(Functions.java:372)
>.... [12:26:03 WARN]: at net.coreprotect.database.Database.insertContainer(Database.java:281)
>.... [12:26:03 WARN]: at net.coreprotect.database.Logger.container_logger(Logger.java:195)
>.... [12:26:03 WARN]: at net.coreprotect.database.Logger.log_container(Logger.java:360)
>.... [12:26:03 WARN]: at net.coreprotect.consumer.Process.processContainerTransaction(Process.java:324)
>.... [12:26:03 WARN]: at net.coreprotect.consumer.Process.processConsumer(Process.java:153)
>.... [12:26:03 WARN]: at net.coreprotect.consumer.Consumer.run(Consumer.java:124)
>.... [12:26:03 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [12:27:10 WARN]: java.io.NotSerializableException: org.bukkit.potion.PotionEffect
>.... [12:27:10 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
>.... [12:27:10 WARN]: at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
>.... [12:27:10 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
>.... [12:27:10 WARN]: at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
>.... [12:27:10 WARN]: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
>.... [12:27:10 WARN]: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
>.... [12:27:10 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
>.... [12:27:10 WARN]: at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
>.... [12:27:10 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
>.... [12:27:10 WARN]: at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
>.... [12:27:10 WARN]: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
>.... [12:27:10 WARN]: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
>.... [12:27:10 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
>.... [12:27:10 WARN]: at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
>.... [12:27:10 WARN]: at java.util.ArrayList.writeObject(ArrayList.java:766)
>.... [12:27:10 WARN]: at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
>.... [12:27:10 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [12:27:10 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [12:27:10 WARN]: at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
>.... [12:27:10 WARN]: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
>.... [12:27:10 WARN]: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
>.... [12:27:10 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
>.... [12:27:10 WARN]: at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
>.... [12:27:10 WARN]: at java.util.ArrayList.writeObject(ArrayList.java:766)
>.... [12:27:10 WARN]: at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
>.... [12:27:10 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [12:27:10 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [12:27:10 WARN]: at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
>.... [12:27:10 WARN]: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
>.... [12:27:10 WARN]: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
>.... [12:27:10 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
>.... [12:27:10 WARN]: at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
>.... [12:27:10 WARN]: at net.coreprotect.Functions.convertByteData(Functions.java:372)
>.... [12:27:10 WARN]: at net.coreprotect.database.Database.insertContainer(Database.java:281)
>.... [12:27:10 WARN]: at net.coreprotect.database.Logger.container_logger(Logger.java:195)
>.... [12:27:10 WARN]: at net.coreprotect.database.Logger.log_container(Logger.java:360)
>.... [12:27:10 WARN]: at net.coreprotect.consumer.Process.processContainerTransaction(Process.java:324)
>.... [12:27:10 WARN]: at net.coreprotect.consumer.Process.processConsumer(Process.java:153)
>.... [12:27:10 WARN]: at net.coreprotect.consumer.Consumer.run(Consumer.java:124)
>.... [12:27:10 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [12:27:16 WARN]: java.io.NotSerializableException: org.bukkit.potion.PotionEffect
>.... [12:27:16 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
>.... [12:27:16 WARN]: at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
>.... [12:27:16 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
>.... [12:27:16 WARN]: at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
>.... [12:27:16 WARN]: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
>.... [12:27:16 WARN]: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
>.... [12:27:16 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
>.... [12:27:16 WARN]: at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
>.... [12:27:16 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
>.... [12:27:16 WARN]: at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
>.... [12:27:16 WARN]: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
>.... [12:27:16 WARN]: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
>.... [12:27:16 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
>.... [12:27:16 WARN]: at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
>.... [12:27:16 WARN]: at java.util.ArrayList.writeObject(ArrayList.java:766)
>.... [12:27:16 WARN]: at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
>.... [12:27:16 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [12:27:16 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [12:27:16 WARN]: at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
>.... [12:27:16 WARN]: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
>.... [12:27:16 WARN]: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
>.... [12:27:16 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
>.... [12:27:16 WARN]: at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
>.... [12:27:16 WARN]: at java.util.ArrayList.writeObject(ArrayList.java:766)
>.... [12:27:16 WARN]: at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
>.... [12:27:16 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [12:27:16 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [12:27:16 WARN]: at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
>.... [12:27:16 WARN]: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
>.... [12:27:16 WARN]: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
>.... [12:27:16 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
>.... [12:27:16 WARN]: at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
>.... [12:27:16 WARN]: at net.coreprotect.Functions.convertByteData(Functions.java:372)
>.... [12:27:16 WARN]: at net.coreprotect.database.Database.insertContainer(Database.java:281)
>.... [12:27:16 WARN]: at net.coreprotect.database.Logger.container_logger(Logger.java:195)
>.... [12:27:16 WARN]: at net.coreprotect.database.Logger.log_container(Logger.java:361)
>.... [12:27:16 WARN]: at net.coreprotect.consumer.Process.processContainerTransaction(Process.java:324)
>.... [12:27:16 WARN]: at net.coreprotect.consumer.Process.processConsumer(Process.java:153)
>.... [12:27:16 WARN]: at net.coreprotect.consumer.Consumer.run(Consumer.java:124)
>.... [12:27:16 WARN]: at java.lang.Thread.run(Thread.java:748)
```

**Comment by Dymeth** [comment]
Same error on Paper 1.14.4 (build 230).
![image](https://user-images.githubusercontent.com/21080646/70181472-fd8d1600-16f2-11ea-9369-d6b739d36aeb.png)

**Comment by a3s** [comment]
Any update on this?

**Comment by In77** [comment]
This can be fixed by changing your MySQL DB character set to **utf8mb4_general_ci**
<img width="227" alt="Screenshot 2019-12-08 at 14 00 48" src="https://user-images.githubusercontent.com/44344308/70384956-25b29880-19c3-11ea-8d9f-77784e92265e.png">

**Comment by Dymeth** [comment]
> This can be fixed by changing your MySQL DB character set to **utf8mb4_general_ci**
> <img alt="Screenshot 2019-12-08 at 14 00 48" width="227" src="https://user-images.githubusercontent.com/44344308/70384956-25b29880-19c3-11ea-8d9f-77784e92265e.png">

Is there a solution for flat DB?
