### ISSUE TITLE
Server background error message

### ISSUE THREAD

**Issue by AUndead** [PlayPro/CoreProtect#207]
[10:16:09 WARN]: org.sqlite.SQLiteException: [SQLITE_IOERR_FSYNC]  I/O error in the VFS layer while trying to flush previously written content (disk I/O error)
[10:16:09 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1030)
[10:16:09 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1042)
[10:16:09 WARN]:        at org.sqlite.core.DB.throwex(DB.java:1007)
[10:16:09 WARN]:        at org.sqlite.core.NativeDB._exec_utf8(Native Method)
[10:16:09 WARN]:        at org.sqlite.core.NativeDB._exec(NativeDB.java:97)
[10:16:09 WARN]:        at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:102)
[10:16:09 WARN]:        at [C-查询]CoreProtect-21.2.jar//net.coreprotect.database.Database.performCheckpoint(Database.java:94)
[10:16:09 WARN]:        at [C-查询]CoreProtect-21.2.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:77)
[10:16:09 WARN]:        at [C-查询]CoreProtect-21.2.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[10:16:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[10:16:10 WARN]: org.sqlite.SQLiteException: [SQLITE_IOERR_FSYNC]  I/O error in the VFS layer while trying to flush previously written content (disk I/O error)
[10:16:10 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1030)
[10:16:10 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1042)
[10:16:10 WARN]:        at org.sqlite.core.DB.throwex(DB.java:1007)
[10:16:10 WARN]:        at org.sqlite.core.NativeDB._exec_utf8(Native Method)
[10:16:10 WARN]:        at org.sqlite.core.NativeDB._exec(NativeDB.java:97)
[10:16:10 WARN]:        at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:102)
[10:16:10 WARN]:        at [C-查询]CoreProtect-21.2.jar//net.coreprotect.database.Database.performCheckpoint(Database.java:94)
[10:16:10 WARN]:        at [C-查询]CoreProtect-21.2.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:77)
[10:16:10 WARN]:        at [C-查询]CoreProtect-21.2.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[10:16:10 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
![12](https://user-images.githubusercontent.com/68094548/163697474-c1e8899d-a675-43d7-9c0a-d240bf593682.png)

**Comment by Intelli** [comment]
https://www.sqlite.org/rescode.html#ioerr_fsync

Error doesn't pertain to CoreProtect code.
