### ISSUE TITLE
When move the dispenser with FastAsyncWorldEdit, get an IllegalStateException.

### ISSUE THREAD

**Issue by book000** [PlayPro/CoreProtect#212]
Hello. Thank you for developing a great plugin.
I saw some behavior that I think is a bug and I would like to report it.

I am using FastAsyncWorldEdit and CoreProtect. When I place a dispenser and move it with the `//move` command, an error appears in the console.
A video of this phenomenon actually occurring was taken and is attached below.

https://user-images.githubusercontent.com/8929706/166102534-72ea0e82-7665-422a-8cd8-b65fd58d528a.mp4

## Environments

- Windows 10 21H1 (Build 19043.1645)
- openjdk 17.0.3 2022-04-19 LTS
- PaperMC 1.18.2-313
- CoreProtect [v21.2](https://github.com/PlayPro/CoreProtect/releases/tag/v21.2)
- FastAsyncWorldEdit [v2.1.3-166](https://ci.athion.net/job/FastAsyncWorldEdit/166/)

## Step for reproduce

1. Build a PaperMC server and add the CoreProtect and FastAsyncWorldEdit jar files to the plugins.
2. Login to the server and grant yourself an operator.
3. Place dispenser.
4. Move the installed dispenser with `//move 3` or similar.
5. `java.lang.IllegalStateException` exception is raised in the console.
6. Destroyed log are recorded at the source location, but no placed logs are recorded at the destination location.

## Logs

The following is a log of the exceptions that occurred.

<details>
<summary>Collapsed because long</summary>

```
[19:47:17 WARN]: java.lang.IllegalStateException: Tile is null, asynchronous access? CraftBlock{pos=BlockPosition{x=-5, y=-60, z=6},type=DISPENSER,data=Block{minecraft:dispenser}[facing=up,triggered=false],fluid=net.minecraft.world.level.material.FluidTypeEmpty@2818a07b}
[19:47:17 WARN]:        at com.google.common.base.Preconditions.checkState(Preconditions.java:590)
[19:47:17 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:89)
[19:47:17 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:75)
[19:47:17 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.block.CraftBlockStates.getBlockState(CraftBlockStates.java:263)
[19:47:17 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.block.CraftBlockStates.getBlockState(CraftBlockStates.java:221)
[19:47:17 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.block.CraftBlockStates.getBlockState(CraftBlockStates.java:206)
[19:47:17 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.block.CraftBlock.getState(CraftBlock.java:329)
[19:47:17 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.utility.Util.getContainerContents(Util.java:724)
[19:47:17 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.worldedit.CoreProtectLogger.setBlock(CoreProtectLogger.java:49)
[19:47:17 WARN]:        at FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-166.jar//com.sk89q.worldedit.EditSession.setBlock(EditSession.java:1042)
[19:47:17 WARN]:        at FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-166.jar//com.sk89q.worldedit.math.BlockVector3.setFullBlock(BlockVector3.java:789)
[19:47:17 WARN]:        at FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-166.jar//com.sk89q.worldedit.world.block.BaseBlock.apply(BaseBlock.java:260)
[19:47:17 WARN]:        at FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-166.jar//com.sk89q.worldedit.function.block.BlockReplace.apply(BlockReplace.java:54)
[19:47:17 WARN]:        at FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-166.jar//com.fastasyncworldedit.core.function.block.CombinedBlockCopy.apply(CombinedBlockCopy.java:25)
[19:47:17 WARN]:        at FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-166.jar//com.sk89q.worldedit.function.visitor.RegionVisitor.apply(RegionVisitor.java:172)
[19:47:17 WARN]:        at FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-166.jar//com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:113)
[19:47:17 WARN]:        at FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-166.jar//com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:74)
[19:47:17 WARN]:        at FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-166.jar//com.sk89q.worldedit.function.operation.ForwardExtentCopy.resume(ForwardExtentCopy.java:421)
[19:47:17 WARN]:        at FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-166.jar//com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:74)
[19:47:17 WARN]:        at FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-166.jar//com.sk89q.worldedit.EditSession.moveRegion(EditSession.java:1915)
[19:47:17 WARN]:        at FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-166.jar//com.sk89q.worldedit.command.RegionCommands.move(RegionCommands.java:577)
[19:47:17 WARN]:        at FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-166.jar//com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_move(RegionCommandsRegistration.java:901)
[19:47:17 WARN]:        at FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-166.jar//org.enginehub.piston.CommandManager.execute(CommandManager.java:157)
[19:47:17 WARN]:        at FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-166.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:730)
[19:47:17 WARN]:        at FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-166.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:751)
[19:47:17 WARN]:        at FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-166.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:732)
[19:47:17 WARN]:        at FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-166.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:702)
[19:47:17 WARN]:        at FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-166.jar//com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672)
[19:47:17 WARN]:        at FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-166.jar//com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:28)
[19:47:17 WARN]:        at FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-166.jar//com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:45)
[19:47:17 WARN]:        at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
[19:47:17 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[19:47:17 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[19:47:17 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[19:47:17 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[19:47:17 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
</details>

I look forward to your reply.

**Comment by Intelli** [comment]
Fixed in https://github.com/PlayPro/CoreProtect/commit/026b9ce322f230ffb33672f6605f96df6958382e
