### ISSUE TITLE
v21.2 Error on loading 1.19 papermc

### ISSUE THREAD

**Issue by TechRoot** [PlayPro/CoreProtect#247]
[02:47:12 INFO]: [CoreProtect] Enabling CoreProtect v21.2
[02:47:12 WARN]: java.lang.NumberFormatException: For input string: "0162000877589"
[02:47:12 WARN]:        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
[02:47:12 WARN]:        at java.base/java.lang.Integer.parseInt(Integer.java:668)
[02:47:12 WARN]:        at java.base/java.lang.Integer.parseInt(Integer.java:786)
[02:47:12 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.utility.Util.loadWorldEdit(Util.java:1022)
[02:47:12 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:432)
[02:47:12 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.CoreProtect.onEnable(CoreProtect.java:75)
[02:47:12 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[02:47:12 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[02:47:12 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536)
[02:47:12 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:561)
[02:47:12 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:475)
[02:47:12 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633)
[02:47:12 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419)
[02:47:12 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[02:47:12 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1121)
[02:47:12 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
[02:47:12 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[02:47:12 INFO]: [CoreProtect] CoreProtect has been successfully enabled! 
[02:47:12 INFO]: [CoreProtect] Using SQLite for data storage.
[02:47:12 INFO]: --------------------
[02:47:12 INFO]: [CoreProtect] Enjoy CoreProtect? Join our Discord!
[02:47:12 INFO]: [CoreProtect] Discord: www.coreprotect.net/discord/
[02:47:12 INFO]: --------------------

**Comment by Johnibur** [comment]
This is fixed in [b450f4d](https://github.com/PlayPro/CoreProtect/commit/b450f4d05a87f8f50fd2e8958c374adea9698b9a).

**Comment by Intelli** [comment]
Duplicate of #245 (fixed in #240)

**Comment by davidjpfeiffer** [comment]
If this has been fixed then why is the fixed version not available on Spigot? https://www.spigotmc.org/resources/coreprotect.8631/history

**Comment by davidjpfeiffer** [comment]
@dkim19375 thank you for the response!
