### ISSUE TITLE
Pebblehost server core protect is not working

### ISSUE THREAD

**Issue by JOSHMFRAMEY** [PlayPro/CoreProtect#253]
i cannot get the plugin to work on my server and keep getting thie error 

- [Sun 19:26:20 ERROR Server/PlayerConnection] null
org.bukkit.command.CommandException: Cannot execute command 'co' in plugin CoreProtect v21.2 - plugin is disabled.
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
    at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2307)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2118)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2099)
    at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46)
    at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6)
    at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51)
    at net.minecraft.server.TickTask.run(TickTask.java:18)
    at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153)
    at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400)
    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
    at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126)
    at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377)
    at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370)
    at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136)
    at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
    at net.minecraft.server.MinecraftServer.lambd

**Comment by vacla** [comment]
@JOSHMFRAMEY can you sent the full log file?

**Comment by JOSHMFRAMEY** [comment]
where would i find the full log file for you? newer to this so learning as i go

**Comment by vacla** [comment]
you can find these in /logs/latest.log

**Comment by JOSHMFRAMEY** [comment]
[04:52:17] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[04:52:18] [ServerMain/INFO]: Found new data pack file/bukkit, loading it automatically
[04:52:22] [ServerMain/INFO]: Reloading ResourceManager: Default, bukkit
[04:52:25] [Worker-Main-24/INFO]: Loaded 7 recipes
[04:52:34] [Server thread/INFO]: Starting minecraft server version 1.18.1
[04:52:34] [Server thread/INFO]: Loading properties
[04:52:35] [Server thread/INFO]: This server is running CraftBukkit version 3403-Spigot-f4ff00f-2e61a5f (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)
[04:52:36] [Server thread/INFO]: Debug logging is disabled
[04:52:36] [Server thread/INFO]: Server Ping Player Sample Count: 12
[04:52:36] [Server thread/INFO]: Using 4 threads for Netty based IO
[04:52:36] [Server thread/INFO]: Default game type: SURVIVAL
[04:52:36] [Server thread/INFO]: Generating keypair
[04:52:39] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:25575
[04:52:39] [Server thread/INFO]: Using epoll channel type
[04:52:40] [Server thread/INFO]: Preparing level "world"
[04:52:42] [Server thread/INFO]: -------- World Settings For [world] --------
[04:52:42] [Server thread/INFO]: Cactus Growth Modifier: 100%
[04:52:42] [Server thread/INFO]: Cane Growth Modifier: 100%
[04:52:42] [Server thread/INFO]: Melon Growth Modifier: 100%
[04:52:42] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[04:52:42] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[04:52:42] [Server thread/INFO]: Sapling Growth Modifier: 100%
[04:52:42] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[04:52:42] [Server thread/INFO]: Carrot Growth Modifier: 100%
[04:52:42] [Server thread/INFO]: Potato Growth Modifier: 100%
[04:52:42] [Server thread/INFO]: Wheat Growth Modifier: 100%
[04:52:42] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[04:52:42] [Server thread/INFO]: Vine Growth Modifier: 100%
[04:52:42] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[04:52:42] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[04:52:42] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[04:52:42] [Server thread/INFO]: Kelp Growth Modifier: 100%
[04:52:42] [Server thread/INFO]: Experience Merge Radius: 3.0
[04:52:42] [Server thread/INFO]: Mob Spawn Range: 6
[04:52:42] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[04:52:42] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[04:52:42] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[04:52:42] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[04:52:42] [Server thread/INFO]: Max TNT Explosions: 100
[04:52:42] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[04:52:42] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[04:52:42] [Server thread/INFO]: Item Despawn Rate: 6000
[04:52:42] [Server thread/INFO]: Item Merge Radius: 2.5
[04:52:42] [Server thread/INFO]: View Distance: 10
[04:52:42] [Server thread/INFO]: Simulation Distance: 10
[04:52:42] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[04:52:42] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[04:52:42] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[04:53:12] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[04:53:12] [Server thread/INFO]: Cactus Growth Modifier: 100%
[04:53:12] [Server thread/INFO]: Cane Growth Modifier: 100%
[04:53:12] [Server thread/INFO]: Melon Growth Modifier: 100%
[04:53:12] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[04:53:12] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[04:53:12] [Server thread/INFO]: Sapling Growth Modifier: 100%
[04:53:12] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[04:53:12] [Server thread/INFO]: Carrot Growth Modifier: 100%
[04:53:12] [Server thread/INFO]: Potato Growth Modifier: 100%
[04:53:12] [Server thread/INFO]: Wheat Growth Modifier: 100%
[04:53:12] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[04:53:12] [Server thread/INFO]: Vine Growth Modifier: 100%
[04:53:12] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[04:53:12] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[04:53:12] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[04:53:12] [Server thread/INFO]: Kelp Growth Modifier: 100%
[04:53:12] [Server thread/INFO]: Experience Merge Radius: 3.0
[04:53:12] [Server thread/INFO]: Mob Spawn Range: 6
[04:53:12] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[04:53:12] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[04:53:12] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[04:53:12] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[04:53:12] [Server thread/INFO]: Max TNT Explosions: 100
[04:53:12] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[04:53:12] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[04:53:12] [Server thread/INFO]: Item Despawn Rate: 6000
[04:53:12] [Server thread/INFO]: Item Merge Radius: 2.5
[04:53:12] [Server thread/INFO]: View Distance: 10
[04:53:12] [Server thread/INFO]: Simulation Distance: 10
[04:53:12] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[04:53:12] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[04:53:12] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[04:53:21] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[04:53:21] [Server thread/INFO]: Cactus Growth Modifier: 100%
[04:53:21] [Server thread/INFO]: Cane Growth Modifier: 100%
[04:53:21] [Server thread/INFO]: Melon Growth Modifier: 100%
[04:53:21] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[04:53:21] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[04:53:21] [Server thread/INFO]: Sapling Growth Modifier: 100%
[04:53:21] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[04:53:21] [Server thread/INFO]: Carrot Growth Modifier: 100%
[04:53:21] [Server thread/INFO]: Potato Growth Modifier: 100%
[04:53:21] [Server thread/INFO]: Wheat Growth Modifier: 100%
[04:53:21] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[04:53:21] [Server thread/INFO]: Vine Growth Modifier: 100%
[04:53:21] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[04:53:21] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[04:53:21] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[04:53:21] [Server thread/INFO]: Kelp Growth Modifier: 100%
[04:53:21] [Server thread/INFO]: Experience Merge Radius: 3.0
[04:53:21] [Server thread/INFO]: Mob Spawn Range: 6
[04:53:21] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[04:53:21] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[04:53:21] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[04:53:21] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[04:53:21] [Server thread/INFO]: Max TNT Explosions: 100
[04:53:21] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[04:53:21] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[04:53:21] [Server thread/INFO]: Item Despawn Rate: 6000
[04:53:21] [Server thread/INFO]: Item Merge Radius: 2.5
[04:53:21] [Server thread/INFO]: View Distance: 10
[04:53:21] [Server thread/INFO]: Simulation Distance: 10
[04:53:21] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[04:53:21] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[04:53:21] [Server thread/INFO]: Nerfing mobs spawned from spawners: false

**Comment by JOSHMFRAMEY** [comment]
that one?

**Comment by JOSHMFRAMEY** [comment]
Also thanks for all the help.

**Comment by vacla** [comment]
@JOSHMFRAMEY yeah but I need the whole file where it tries to load coreprotect. you might need to put the whole file in a https://pastebin.com and link it here
