### ISSUE TITLE
Error when starting CoreProtect on 1.19

### ISSUE THREAD

**Issue by DevPanada** [PlayPro/CoreProtect#259]
When starting the server on PaperSpigot 1.19 I get the following error message.
Is this something I should worry about?

```[03:53:52 INFO]: [CoreProtect] Enabling CoreProtect v21.2
[03:53:52 WARN]: java.lang.NumberFormatException: For input string: "0162000877589"
[03:53:52 WARN]:        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
[03:53:52 WARN]:        at java.base/java.lang.Integer.parseInt(Integer.java:668)
[03:53:52 WARN]:        at java.base/java.lang.Integer.parseInt(Integer.java:786)
[03:53:52 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.utility.Util.loadWorldEdit(Util.java:1022)
[03:53:52 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:432)
[03:53:52 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.CoreProtect.onEnable(CoreProtect.java:75)
[03:53:52 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[03:53:52 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[03:53:52 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536)
[03:53:52 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563)
[03:53:52 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477)
[03:53:52 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633)
[03:53:52 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419)
[03:53:52 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[03:53:52 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1121)
[03:53:52 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
[03:53:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by vacla** [comment]
Duplicate of #245

**Comment by DevPanada** [comment]
Ah okay I see, thank you.
