### ISSUE TITLE
NullPointerException when killing a Citizens Player NPC

### ISSUE THREAD

**Issue by BBaoVanC** [PlayPro/CoreProtect#261]
When I kill a Player NPC created with the [Citizens](https://citizensnpcs.co/) plugin, CoreProtect throws a NullPointerException:

```
[02:00:10 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
[02:00:10 WARN]: 	at CoreProtect.jar//net.coreprotect.database.logger.PlayerKillLogger.log(PlayerKillLogger.java:31)
[02:00:10 WARN]: 	at CoreProtect.jar//net.coreprotect.consumer.process.PlayerKillProcess.process(PlayerKillProcess.java:15)
[02:00:10 WARN]: 	at CoreProtect.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:215)
[02:00:10 WARN]: 	at CoreProtect.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[02:00:10 WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by BBaoVanC** [comment]
This is still an issue

**Comment by Intelli** [comment]
Fixed in https://github.com/PlayPro/CoreProtect/commit/319d104622133e757f5c95b22c3844cf09b9d449
