### ISSUE TITLE
java.lang.NumberFormatException: For input string: "0162000877589"

### ISSUE THREAD

**Issue by Dymeth** [PlayPro/CoreProtect#262]
```
[CoreProtect] Enabling CoreProtect v21.2
java.lang.NumberFormatException: For input string: "0162000877589"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at CoreProtect-21.2.jar//net.coreprotect.utility.Util.loadWorldEdit(Util.java:1022)
	at CoreProtect-21.2.jar//net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:432)
	at CoreProtect-21.2.jar//net.coreprotect.CoreProtect.onEnable(CoreProtect.java:75)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563)
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1121)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

WorldEdit version: "7.2.11-beta-01+6200-0877589"
(from https://builds.enginehub.org/job/worldedit?branch=master)

**Comment by vacla** [comment]
Duplicate of #245

**Comment by Dymeth** [comment]
Oups
