### ISSUE TITLE
coreprotect freebsd issues

### ISSUE THREAD

**Issue by aldermath** [PlayPro/CoreProtect#27]
Attempting to run coreprotect on freebsd gives a bunch of sqlite errors:

[18:24:14] [Server thread/INFO]: [CoreProtect] Enabling CoreProtect v19.5
[18:24:14] [Server thread/WARN]: java.sql.SQLException: no such column: 'type'
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:49)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.getString(JDBC3ResultSet.java:444)
[18:24:14] [Server thread/WARN]: at net.coreprotect.Functions.createDatabaseTables(Functions.java:536)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.loadDatabase(ConfigHandler.java:206)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:366)
[18:24:14] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:24:14] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)
[18:24:14] [Server thread/WARN]: java.sql.SQLException: no such column: 'id'
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:49)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.getInt(JDBC3ResultSet.java:400)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.loadWorlds(ConfigHandler.java:293)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:372)
[18:24:14] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:24:14] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)
[18:24:14] [Server thread/WARN]: java.lang.IllegalStateException: Current state = RESET, new state = FLUSHED
[18:24:14] [Server thread/WARN]: at java.base/java.nio.charset.CharsetDecoder.throwIllegalStateException(Unknown Source)
[18:24:14] [Server thread/WARN]: at java.base/java.nio.charset.CharsetDecoder.flush(Unknown Source)
[18:24:14] [Server thread/WARN]: at java.base/java.nio.charset.CharsetDecoder.decode(Unknown Source)
[18:24:14] [Server thread/WARN]: at java.base/java.nio.charset.Charset.decode(Unknown Source)
[18:24:14] [Server thread/WARN]: at org.sqlite.core.NativeDB.utf8ByteBufferToString(NativeDB.java:507)
[18:24:14] [Server thread/WARN]: at org.sqlite.core.NativeDB.column_name(NativeDB.java:239)
[18:24:14] [Server thread/WARN]: at org.sqlite.core.DB.column_names(DB.java:733)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3Statement.getResultSet(JDBC3Statement.java:131)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:73)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.loadTypes(ConfigHandler.java:246)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:373)
[18:24:14] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:24:14] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)
[18:24:14] [Server thread/WARN]: java.sql.SQLException: no such column: 'version'
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:49)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.getString(JDBC3ResultSet.java:444)
[18:24:14] [Server thread/WARN]: at net.coreprotect.patch.Patch.getDatabaseVersion(Patch.java:57)
[18:24:14] [Server thread/WARN]: at net.coreprotect.patch.Patch.versionCheck(Patch.java:235)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:388)
[18:24:14] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:24:14] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)
[18:24:14] [Server thread/WARN]: java.sql.SQLException: no such column: 'version'
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:49)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.getString(JDBC3ResultSet.java:444)
[18:24:14] [Server thread/WARN]: at net.coreprotect.patch.Patch.getDatabaseVersion(Patch.java:57)
[18:24:14] [Server thread/WARN]: at net.coreprotect.patch.Patch.versionCheck(Patch.java:236)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:388)
[18:24:14] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:24:14] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Intelli** [comment]
Please do the following:

1. Stop the server
2. Rename the CoreProtect database.db file to database.db.bak
3. Start your server
4. Attach your latest.log file here

**Comment by aldermath** [comment]
[latest.log](https://github.com/PlayPro/CoreProtect/files/6621332/latest.log)
[hs_err_pid84965.log](https://github.com/PlayPro/CoreProtect/files/6621333/hs_err_pid84965.log)
The server hard crashes before anything useful is placed in the server log. I attached an extra crash log that has the minecraft errors in it

**Comment by aldermath** [comment]
Here's a snippet of an older log with similar errors:

[18:24:14] [Server thread/INFO]: [CoreProtect] Enabling CoreProtect v19.5
[18:24:14] [Server thread/WARN]: java.sql.SQLException: no such column: 'type'
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:49)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.getString(JDBC3ResultSet.java:444)
[18:24:14] [Server thread/WARN]: at net.coreprotect.Functions.createDatabaseTables(Functions.java:536)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.loadDatabase(ConfigHandler.java:206)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:366)
[18:24:14] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:24:14] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)
[18:24:14] [Server thread/WARN]: java.sql.SQLException: no such column: 'id'
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:49)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.getInt(JDBC3ResultSet.java:400)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.loadWorlds(ConfigHandler.java:293)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:372)
[18:24:14] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:24:14] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)
[18:24:14] [Server thread/WARN]: java.lang.IllegalStateException: Current state = RESET, new state = FLUSHED
[18:24:14] [Server thread/WARN]: at java.base/java.nio.charset.CharsetDecoder.throwIllegalStateException(Unknown Source)
[18:24:14] [Server thread/WARN]: at java.base/java.nio.charset.CharsetDecoder.flush(Unknown Source)
[18:24:14] [Server thread/WARN]: at java.base/java.nio.charset.CharsetDecoder.decode(Unknown Source)
[18:24:14] [Server thread/WARN]: at java.base/java.nio.charset.Charset.decode(Unknown Source)
[18:24:14] [Server thread/WARN]: at org.sqlite.core.NativeDB.utf8ByteBufferToString(NativeDB.java:507)
[18:24:14] [Server thread/WARN]: at org.sqlite.core.NativeDB.column_name(NativeDB.java:239)
[18:24:14] [Server thread/WARN]: at org.sqlite.core.DB.column_names(DB.java:733)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3Statement.getResultSet(JDBC3Statement.java:131)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:73)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.loadTypes(ConfigHandler.java:246)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:373)
[18:24:14] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:24:14] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)
[18:24:14] [Server thread/WARN]: java.sql.SQLException: no such column: 'version'
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:49)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.getString(JDBC3ResultSet.java:444)
[18:24:14] [Server thread/WARN]: at net.coreprotect.patch.Patch.getDatabaseVersion(Patch.java:57)
[18:24:14] [Server thread/WARN]: at net.coreprotect.patch.Patch.versionCheck(Patch.java:235)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:388)
[18:24:14] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:24:14] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)
[18:24:14] [Server thread/WARN]: java.sql.SQLException: no such column: 'version'
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:49)
[18:24:14] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3ResultSet.getString(JDBC3ResultSet.java:444)
[18:24:14] [Server thread/WARN]: at net.coreprotect.patch.Patch.getDatabaseVersion(Patch.java:57)
[18:24:14] [Server thread/WARN]: at net.coreprotect.patch.Patch.versionCheck(Patch.java:236)
[18:24:14] [Server thread/WARN]: at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:388)
[18:24:14] [Server thread/WARN]: at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:24:14] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[18:24:14] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[18:24:14] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:24:14] [Server thread/WARN]: at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Intelli** [comment]
This is likely an issue specific to your system (involving the SQLite driver).

Are you able to run any other plugins that utilize SQLite?

**Comment by aldermath** [comment]
worldguard crashes after installing and restarting once with similar errors. I guess it's a sqlite thing but I have no idea how to fix it. I tried installing different versions on the host but they all failed.

**Comment by Intelli** [comment]
If you’re unable to resolve the issue, you may wish to consider using MySQL instead.

I’ll test FreeBSD 12.2 tomorrow to attempt to replicate your issue.

**Comment by aldermath** [comment]
I have a suspicion that it is the specific defaults that truenas jails set up that are the issue. It will probably work on a regular freebsd install. If you get it working let me know what versions of sqlite packages you have installed.

**Comment by Intelli** [comment]
I receive this SQLite related error on startup with FreeBSD 12.2:

`[17:25:47 WARN]: java.lang.IllegalStateException: Current state = RESET, new state = FLUSHED
[17:25:47 WARN]: 	at java.nio.charset.CharsetDecoder.throwIllegalStateException(CharsetDecoder.java:992)
[17:25:47 WARN]: 	at java.nio.charset.CharsetDecoder.flush(CharsetDecoder.java:675)
[17:25:47 WARN]: 	at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:804)
[17:25:47 WARN]: 	at java.nio.charset.Charset.decode(Charset.java:807)
[17:25:47 WARN]: 	at org.sqlite.core.NativeDB.utf8ByteBufferToString(NativeDB.java:507)
[17:25:47 WARN]: 	at org.sqlite.core.NativeDB.column_name(NativeDB.java:239)
[17:25:47 WARN]: 	at org.sqlite.core.DB.column_names(DB.java:733)
[17:25:47 WARN]: 	at org.sqlite.jdbc3.JDBC3Statement.getResultSet(JDBC3Statement.java:131)
[17:25:47 WARN]: 	at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:73)
[17:25:47 WARN]: 	at net.coreprotect.Functions.createDatabaseTables(Functions.java:534)
[17:25:47 WARN]: 	at net.coreprotect.config.ConfigHandler.loadDatabase(ConfigHandler.java:206)
[17:25:47 WARN]: 	at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:366)
[17:25:47 WARN]: 	at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72)
[17:25:47 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[17:25:47 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[17:25:47 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[17:25:47 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[17:25:47 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[17:25:47 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[17:25:47 WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[17:25:47 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[17:25:47 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
`

**Comment by Intelli** [comment]
As far as I can tell, this may be a bug with the SQLite JDBC Driver. The issue isn't present on other systems.

I tested with Java 8, Java 11, and Java 16, and also tested compiling the plugin with those versions. Unfortunately, the issue persisted across all Java versions.

You may wish to submit a bug report here: https://github.com/xerial/sqlite-jdbc

**Comment by aldermath** [comment]
This seems to be an issue with newer versions of sqlite. Paper 1.16.4-363 updated the dependency from 3.32 to 3.34. if you use an older version of paper with the lower dependancy it seems to work.

**Comment by Intelli** [comment]
Definitely a JDBC driver bug then.
