### ISSUE TITLE
NumberformatException on startup

### ISSUE THREAD

**Issue by Wolvinny** [PlayPro/CoreProtect#281]
Hello,
I've been getting the following error every time i start
```
17.08 02:00:49 [Server] INFO [CoreProtect] Enabling CoreProtect v21.2
17.08 02:00:50 [Server]  java.lang.NumberFormatException: For input string: "0162000877589"
17.08 02:00:50 [Server]  at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
17.08 02:00:50 [Server]  at java.base/java.lang.Integer.parseInt(Integer.java:668)
17.08 02:00:50 [Server]  at java.base/java.lang.Integer.parseInt(Integer.java:786)
17.08 02:00:50 [Server]  at CoreProtect-21.2.jar//net.coreprotect.utility.Util.loadWorldEdit(Util.java:1022)
17.08 02:00:50 [Server]  at CoreProtect-21.2.jar//net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:432)
17.08 02:00:50 [Server]  at CoreProtect-21.2.jar//net.coreprotect.CoreProtect.onEnable(CoreProtect.java:75)
17.08 02:00:50 [Server]  at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
17.08 02:00:50 [Server]  at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
17.08 02:00:50 [Server]  at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
17.08 02:00:50 [Server]  at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
17.08 02:00:50 [Server]  at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
17.08 02:00:50 [Server]  at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
17.08 02:00:50 [Server]  at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422)
17.08 02:00:50 [Server]  at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
17.08 02:00:50 [Server]  at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1125)
17.08 02:00:50 [Server]  at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
17.08 02:00:50 [Server]  at java.base/java.lang.Thread.run(Thread.java:831)
```
i dont know whether this is a known issue but couldnt find anything on it, so hereby

**Comment by vacla** [comment]
Duplicate of #245
