### ISSUE TITLE
1.16.5 error

### ISSUE THREAD

**Issue by StrictMaple** [PlayPro/CoreProtect#289]
Could not load 'plugins\CoreProtect-21.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: net/coreprotect/CoreProtect has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:148) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:393) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:388) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:212) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:771) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_341]
Caused by: java.lang.UnsupportedClassVersionError: net/coreprotect/CoreProtect has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_341]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_341]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_341]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:253) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:176) ~[forge:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_341]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:116) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:111) ~[forge:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_341]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_341]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_341]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:144) ~[forge:?]
        ... 7 more

**Comment by vacla** [comment]
@StrictMaple you need to update to java 11.
