### ISSUE TITLE
error in console

### ISSUE THREAD

**Issue by kenuna** [PlayPro/CoreProtect#311]
Could not pass event AsyncChatEvent to CoreProtect v21.3
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:829) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:328) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:519) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:474) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.16.5.jar:git-Paper-794]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-794]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.kyori.adventure.text.serializer.plain.PlainTextComponentSerializer.plainText(PlainTextComponentSerializer.java:53) ~[?:?]
	at net.coreprotect.paper.listener.PaperChatListener.onPlayerChat(PaperChatListener.java:17) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor394.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
	at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:225) ~[patched_1.16.5.jar:git-Paper-794]
	at io.papermc.paper.adventure.ChatProcessor.processModern(ChatProcessor.java:130) ~[patched_1.16.5.jar:git-Paper-794]
	at io.papermc.paper.adventure.ChatProcessor.lambda$process$1(ChatProcessor.java:68) ~[patched_1.16.5.jar:git-Paper-794]
	at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:120) ~[patched_1.16.5.jar:git-Paper-794]
	at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:65) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:2102) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2017) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1955) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:43) ~[patched_1.16.5.jar:git-Paper-794]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
	

if a player sends something to the chat, then an error is detected, how do I fix this error

**Comment by Intelli** [comment]
Please try re-downloading the CoreProtect plugin file, and if the error persists, please provide a full copy of your server log.
