### ISSUE TITLE
SQLite Issue

### ISSUE THREAD

**Issue by sudapeople** [PlayPro/CoreProtect#320]
org.sqlite.SQLiteException: [SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed)
at org.sqlite.core.DB.newSQLException(DB.java:1030)
at org.sqlite.core.DB.newSQLException(DB.java:1042)
at org.sqlite.core.DB.throwex(DB.java:1007)
at org.sqlite.core.DB.executeBatch(DB.java:832)
at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:64)
at CoreProtect-21.3.jar//net.coreprotect.consumer.process.Process.commit(Process.java:283)
at CoreProtect-21.3.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:248)
at CoreProtect-21.3.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)

**Comment by Intelli** [comment]
> The database disk image is malformed (database disk image is malformed)

Your `database.db` file is corrupt. You can either attempt a purge to repair it, or delete the file to start a new database.

The most common cause of database file corruption is from using a copy of the file that was made while the server was still running.
