### ISSUE TITLE
PreLogEvent error during shutdown

### ISSUE THREAD

**Issue by zThana** [PlayPro/CoreProtect#338]
Getting this error during server shutdown (/stop).
```java
[Server thread/INFO] [CoreProtect/]: Disabling CoreProtect v21.2
[Server thread/INFO] [Minecraft/]: [CoreProtect] Finishing up data logging. Please wait...
[Thread-55/INFO] [STDERR/]: [net.coreprotect.database.logger.ItemLogger:logTransaction:143]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[Thread-55/INFO] [STDERR/]: [net.coreprotect.database.logger.ItemLogger:logTransaction:143]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[Thread-55/INFO] [STDERR/]: [net.coreprotect.database.logger.ItemLogger:logTransaction:143]: 	at net.coreprotect.database.logger.ItemLogger.logTransaction(ItemLogger.java:128)
[Thread-55/INFO] [STDERR/]: [net.coreprotect.database.logger.ItemLogger:logTransaction:143]: 	at net.coreprotect.database.logger.ItemLogger.log(ItemLogger.java:103)
[Thread-55/INFO] [STDERR/]: [net.coreprotect.database.logger.ItemLogger:logTransaction:143]: 	at net.coreprotect.consumer.process.ItemTransactionProcess.process(ItemTransactionProcess.java:27)
[Thread-55/INFO] [STDERR/]: [net.coreprotect.database.logger.ItemLogger:logTransaction:143]: 	at net.coreprotect.consumer.process.Process.processConsumer(Process.java:155)
[Thread-55/INFO] [STDERR/]: [net.coreprotect.database.logger.ItemLogger:logTransaction:143]: 	at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[Thread-55/INFO] [STDERR/]: [net.coreprotect.database.logger.ItemLogger:logTransaction:143]: 	at java.base/java.lang.Thread.run(Thread.java:829)```

**Comment by Intelli** [comment]
Please provide your full server log.
