### ISSUE TITLE
Error when stopping server

### ISSUE THREAD

**Issue by Gavins38** [PlayPro/CoreProtect#345]
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[11:36:16 ERROR] [STDERR]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[11:36:16 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[11:36:16 ERROR] [STDERR]:      at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:36:16 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)

I get this error whenever I stop my server

**Comment by Intelli** [comment]
Forge is not officially supported.
