### ISSUE TITLE
What is the problem, tell me?

### ISSUE THREAD

**Issue by Rasolan4K** [PlayPro/CoreProtect#36]
[06:03:33 ERROR]: Error occurred while enabling CoreProtect v19.5 (Is it up to date?)
java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-16-openjdk-amd64/lib/libawt_xawt.so
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2387) ~[?:?]
        at java.lang.Runtime.load0(Runtime.java:746) ~[?:?]
        at java.lang.System.load(System.java:1857) ~[?:?]
        at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
        at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383) ~[?:?]
        at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227) ~[?:?]
        at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169) ~[?:?]
        at jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:310) ~[?:?]
        at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:280) ~[?:?]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2392) ~[?:?]
        at java.lang.Runtime.loadLibrary0(Runtime.java:808) ~[?:?]
        at java.lang.System.loadLibrary(System.java:1893) ~[?:?]
        at java.awt.Toolkit$2.run(Toolkit.java:1389) ~[?:?]
        at java.awt.Toolkit$2.run(Toolkit.java:1387) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:312) ~[?:?]
        at java.awt.Toolkit.loadLibraries(Toolkit.java:1386) ~[?:?]
        at java.awt.Toolkit.<clinit>(Toolkit.java:1419) ~[?:?]
        at java.awt.Color.<clinit>(Color.java:275) ~[?:?]
        at net.md_5.bungee.api.ChatColor.<clinit>(ChatColor.java:39) ~[patched_1.17.jar:git-Paper-79]
        at net.coreprotect.bukkit.Bukkit_v1_16.<init>(Bukkit_v1_16.java:29) ~[?:?]
        at net.coreprotect.bukkit.BukkitAdapter.loadAdapter(BukkitAdapter.java:39) ~[?:?]
        at net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:362) ~[?:?]
        at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:72) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-79]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-79]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-79]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-79]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-79]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[patched_1.17.jar:git-Paper-79]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:304) ~[patched_1.17.jar:git-Paper-79]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-79]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-79]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by vacla** [comment]
@Rasolan4K this is very likely the headless version, try installing the normal version

**Comment by Intelli** [comment]
Resolved in Discord. Issue was fixed by installing openjdk-16-jdk
