### ISSUE TITLE
update 1.20 please

### ISSUE THREAD

**Issue by joaoespanhol** [PlayPro/CoreProtect#378]
update 1.20 please

**Comment by vacla** [comment]
@joaoespanhol coreprotect should work on 1.20

**Comment by lordofpipes** [comment]
Currently, hanging sign text saving is not working

**Comment by CleMooling** [comment]
> Currently, hanging sign text saving is not working

That's right, Mojang may changed sign work, and most plugins which works for sign is need to be updated.

**Comment by PanetiX** [comment]
I get this error on Paper 1.20.1:

`[13:38:14] [Thread-41/WARN]: org.sqlite.SQLiteException: [SQLITE_CORRUPT] The database disk image is malformed (database disk image is malformed)
[13:38:14] [Thread-41/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1179)
[13:38:14] [Thread-41/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1190)
[13:38:14] [Thread-41/WARN]: 	at org.sqlite.core.DB.throwex(DB.java:1150)
[13:38:14] [Thread-41/WARN]: 	at org.sqlite.core.DB.executeBatch(DB.java:951)
[13:38:14] [Thread-41/WARN]: 	at org.sqlite.core.DB.lambda$executeBatch$0(DB.java:916)
[13:38:14] [Thread-41/WARN]: 	at org.sqlite.core.SafeStmtPtr.safeRun(SafeStmtPtr.java:128)
[13:38:14] [Thread-41/WARN]: 	at org.sqlite.core.DB.executeBatch(DB.java:916)
[13:38:14] [Thread-41/WARN]: 	at org.sqlite.core.CorePreparedStatement.lambda$executeLargeBatch$1(CorePreparedStatement.java:76)
[13:38:14] [Thread-41/WARN]: 	at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454)
[13:38:14] [Thread-41/WARN]: 	at org.sqlite.core.CorePreparedStatement.executeLargeBatch(CorePreparedStatement.java:72)
[13:38:14] [Thread-41/WARN]: 	at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:58)
[13:38:14] [Thread-41/WARN]: 	at CoreProtect-21.3.jar//net.coreprotect.consumer.process.Process.commit(Process.java:285)
[13:38:14] [Thread-41/WARN]: 	at CoreProtect-21.3.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:248)
[13:38:14] [Thread-41/WARN]: 	at CoreProtect-21.3.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[13:38:14] [Thread-41/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by ehx-v1** [comment]
So from what I understand, CoreProtect mostly works in 1.20, but some few blocks aren't properly supported?

**Comment by 42Willow** [comment]
> So from what I understand, CoreProtect mostly works in 1.20, but some few blocks aren't properly supported?

Yes, the new 1.20 blocks are not supported.

**Comment by LucidAPs** [comment]
@Intelli Be like, "bugs and requests goes to github" 
Intelli on github "[invalid]"

You are a garbage developer charging people monthly for a minecraft version support, while also pretending that everyone is crazy and just not following proper procedure for reporting "bugs" when in reality its so obvious that this whole thing is a desperate attempt to get more patreons.

Instead of actually working and charging for features and improvements to make some money, you chose this method. Garbage.

**Comment by 42Willow** [comment]
I also don't think this issue should be marked as invalid.

Is this repo updated to 1.20? Or is that closed source? I'd like to know so I can compile this locally to get support for the new 1.20 blocks.

**Comment by vacla** [comment]
Github has currently the 1.20 version but intelli mentioned that it won't be released this month publically

**Comment by 42Willow** [comment]
Thanks creator of Watson :)

That's great, I can compile it myself then.

**Comment by mov51** [comment]
> @Intelli Be like, "bugs and requests goes to github" Intelli on github "[invalid]"
> 
> You are a garbage developer charging people monthly for a minecraft version support, while also pretending that everyone is crazy and just not following proper procedure for reporting "bugs" when in reality its so obvious that this whole thing is a desperate attempt to get more patreons.
> 
> Instead of actually working and charging for features and improvements to make some money, you chose this method. Garbage.

They're not "charging monthly for version support" they're providing early access to compiled version of the plugin to patrons who support the development and actually pay for the skills required to develop a plugin. They've done that for years, including by releasing RCs for the 1.19 release exclusively on Patreon, and it doesn't change that it will be released publicly. 
As mentioned above you can compile the GitHub code if you're technically inclined and are willing to deal with the risks.

**Comment by ehx-v1** [comment]
Everyone please just ignore @LucidAPs and their comment. Not sure if they're a hater or a troll, but neither deserves attention.

**Comment by Intelli** [comment]
> ~I also don't think this issue should be marked as invalid. If an issue is believed to be invalid shouldn't it be closed?~ Never mind the source code is 1.20
> 
> Is this repo updated to 1.20? Or is that closed source? I'd like to know so I can compile this locally to get support for the new 1.20 blocks.
> 
> It's great that this is being maintained for pretty much free - thanks for the great plugin.

The next release of CoreProtect is still under development, and yes, all the changes are in this repo. 

This issue was marked invalid as it doesn’t actually request any specific functionality. The previous release of CoreProtect (v21.3) already supports Minecraft 1.20 blocks/items/entities.

**Comment by Intelli** [comment]
@LucidAP Your GitHub account is now being blocked from this repo for violating our code of conduct, which can be found in CONTRIBUTING.md

https://github.com/PlayPro/CoreProtect/blob/master/CONTRIBUTING.md#code-of-conduct
