### ISSUE TITLE
Cannot invoke "org.bukkit.entity.EntityType.name()" because "type" is null

### ISSUE THREAD

**Issue by DexterSK** [PlayPro/CoreProtect#401]
[13:12:10 ERROR]: [dough: protection] An Error occured while logging for the Protection Module: "CoreProtect"
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.EntityType.name()" because "type" is null
        at net.coreprotect.utility.Util.getEntityId(Util.java:800) ~[CoreProtect-21.3.jar:?]
        at net.coreprotect.utility.Util.getSpawnerType(Util.java:900) ~[CoreProtect-21.3.jar:?]
        at net.coreprotect.consumer.Queue.queueBlockBreak(Queue.java:103) ~[CoreProtect-21.3.jar:?]
        at net.coreprotect.consumer.Queue.queueBlockBreak(Queue.java:84) ~[CoreProtect-21.3.jar:?]
        at net.coreprotect.CoreProtectAPI.logRemoval(CoreProtectAPI.java:331) ~[CoreProtect-21.3.jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.loggers.CoreProtectLogger.logAction(CoreProtectLogger.java:34) ~[Slimefun4.jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.logAction(ProtectionManager.java:191) ~[Slimefun4.jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.onBlockPlace(BlockListener.java:89) ~[Slimefun4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor296.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-1995]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:415) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:413) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:601) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2043) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by vacla** [comment]
Duplicate of https://github.com/PlayPro/CoreProtect/issues/380

**Comment by DexterSK** [comment]
oh sorry
