### ISSUE TITLE
folia "r:#global"

### ISSUE THREAD

**Issue by 347180440** [PlayPro/CoreProtect#413]
Using "r:#global" in Folia only recovers a block or two next to it and then stops responding

**Comment by Intelli** [comment]
Unable to replicate. Please provide a copy of your log file.

**Comment by 347180440** [comment]
[03:59:07] [Region Scheduler Thread #0/INFO]: Li_HuaJian issued server command: /co rollback user:#tnt radius:-1 time:1h exclude:tnt
[03:59:09] [Region Scheduler Thread #0/WARN]: java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.iterator()" because "data" is null
[03:59:09] [Region Scheduler Thread #0/WARN]: 	at CoreProtect-21.3.jar//net.coreprotect.database.Rollback.lambda$performRollbackRestore$1(Rollback.java:356)
[03:59:09] [Region Scheduler Thread #0/WARN]: 	at CoreProtect-21.3.jar//net.coreprotect.thread.Scheduler.lambda$scheduleSyncDelayedTask$0(Scheduler.java:25)
[03:59:09] [Region Scheduler Thread #0/WARN]: 	at io.papermc.paper.threadedregions.scheduler.FoliaRegionScheduler$LocationScheduledTask.run(FoliaRegionScheduler.java:329)
[03:59:09] [Region Scheduler Thread #0/WARN]: 	at io.papermc.paper.threadedregions.scheduler.FoliaRegionScheduler$Scheduler.tick(FoliaRegionScheduler.java:270)
[03:59:09] [Region Scheduler Thread #0/WARN]: 	at io.papermc.paper.threadedregions.scheduler.FoliaRegionScheduler.tick(FoliaRegionScheduler.java:143)
[03:59:09] [Region Scheduler Thread #0/WARN]: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1489)
[03:59:09] [Region Scheduler Thread #0/WARN]: 	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:367)
[03:59:09] [Region Scheduler Thread #0/WARN]: 	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:388)
[03:59:09] [Region Scheduler Thread #0/WARN]: 	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525)
[03:59:09] [Region Scheduler Thread #0/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by 347180440** [comment]
[03:59:07] [Region Scheduler Thread #0/INFO]: Li_HuaJian issued server command: /co rollback user:#tnt radius:-1 time:1h exclude:tnt
[03:59:09] [Region Scheduler Thread #0/WARN]: java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.iterator()" because "data" is null
[03:59:09] [Region Scheduler Thread #0/WARN]: 	at CoreProtect-21.3.jar//net.coreprotect.database.Rollback.lambda$performRollbackRestore$1(Rollback.java:356)
[03:59:09] [Region Scheduler Thread #0/WARN]: 	at CoreProtect-21.3.jar//net.coreprotect.thread.Scheduler.lambda$scheduleSyncDelayedTask$0(Scheduler.java:25)
[03:59:09] [Region Scheduler Thread #0/WARN]: 	at io.papermc.paper.threadedregions.scheduler.FoliaRegionScheduler$LocationScheduledTask.run(FoliaRegionScheduler.java:329)
[03:59:09] [Region Scheduler Thread #0/WARN]: 	at io.papermc.paper.threadedregions.scheduler.FoliaRegionScheduler$Scheduler.tick(FoliaRegionScheduler.java:270)
[03:59:09] [Region Scheduler Thread #0/WARN]: 	at io.papermc.paper.threadedregions.scheduler.FoliaRegionScheduler.tick(FoliaRegionScheduler.java:143)
[03:59:09] [Region Scheduler Thread #0/WARN]: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1489)
[03:59:09] [Region Scheduler Thread #0/WARN]: 	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:367)
[03:59:09] [Region Scheduler Thread #0/WARN]: 	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:388)
[03:59:09] [Region Scheduler Thread #0/WARN]: 	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525)
[03:59:09] [Region Scheduler Thread #0/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Intelli** [comment]
CoreProtect v21.3 doesn't support Folia. Assuming you're running a custom build, then your build is out of date, as this was already fixed: https://github.com/PlayPro/CoreProtect/commit/d7d53bf9e2f8f97ff9bfcb8df0c751dde2d1e772
