### ISSUE TITLE
1.19.4 CoreProtect error

### ISSUE THREAD

**Issue by bobhenl** [PlayPro/CoreProtect#425]
[17:20:02 ERROR]: Could not pass event SignChangeEvent to CoreProtect v22.0
java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 4
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R3.block.sign.CraftSignSide.line(CraftSignSide.java:34) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.block.CraftSign.line(CraftSign.java:34) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.coreprotect.paper.Paper_v1_17.getLine(Paper_v1_17.java:12) ~[CoreProtect-22.0.jar:?]
        at net.coreprotect.listener.player.SignChangeListener.onSignChange(SignChangeListener.java:56) ~[CoreProtect-22.0.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1985]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.updateSignText(ServerGamePacketListenerImpl.java:3582) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleSignUpdate$27(ServerGamePacketListenerImpl.java:3532) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:20:06 INFO]: Alex_the_striker issued server command: /pm LightStrike216 no
[17:20:07 WARN]: java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 4
[17:20:07 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[17:20:07 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[17:20:07 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[17:20:07 WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:361)
[17:20:07 WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
[17:20:07 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.block.sign.CraftSignSide.line(CraftSignSide.java:34)
[17:20:07 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.block.CraftSign.line(CraftSign.java:34)
[17:20:07 WARN]:        at CoreProtect-22.0.jar//net.coreprotect.paper.Paper_v1_17.getLine(Paper_v1_17.java:12)
[17:20:07 WARN]:        at CoreProtect-22.0.jar//net.coreprotect.listener.block.BlockPlaceListener.onBlockPlace(BlockPlaceListener.java:118)
[17:20:07 WARN]:        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[17:20:07 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[17:20:07 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:20:07 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[17:20:07 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[17:20:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[17:20:07 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:415)
[17:20:07 WARN]:        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:409)
[17:20:07 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:600)
[17:20:07 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2041)
[17:20:07 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[17:20:07 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[17:20:07 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
[17:20:07 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:20:07 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[17:20:07 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[17:20:07 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1369)
[17:20:07 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[17:20:07 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[17:20:07 WARN]:        at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1346)
[17:20:07 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1339)
[17:20:07 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[17:20:07 WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1317)
[17:20:07 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1205)
[17:20:07 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[17:20:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:20:07 INFO]: [standard] sanicspeed2560: ...
[17:20:10 ERROR]: Could not pass event SignChangeEvent to CoreProtect v22.0
java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 4
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R3.block.sign.CraftSignSide.line(CraftSignSide.java:34) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.block.CraftSign.line(CraftSign.java:34) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.coreprotect.paper.Paper_v1_17.getLine(Paper_v1_17.java:12) ~[CoreProtect-22.0.jar:?]
        at net.coreprotect.listener.player.SignChangeListener.onSignChange(SignChangeListener.java:56) ~[CoreProtect-22.0.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1985]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.updateSignText(ServerGamePacketListenerImpl.java:3582) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleSignUpdate$27(ServerGamePacketListenerImpl.java:3532) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by xlifi** [comment]
fixed in [8459181](https://github.com/PlayPro/CoreProtect/commit/8459181f770f1103bf9769bf587ba491e59322c4), wait for release
