### ISSUE TITLE
[bug] Bug at new version

### ISSUE THREAD

**Issue by ostermine** [PlayPro/CoreProtect#428]
sometimes its sends me (and spam) at new version `CoreProtect-22.0` at paper 1.19.2 `paper-1.19.2-307`

```
[14:20:08 ERROR]: Could not pass event SignChangeEvent to CoreProtect v22.0
java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 4
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.block.CraftSign.line(CraftSign.java:35) ~[paper-1.19.2.jar:git-Paper-307]
        at net.coreprotect.paper.Paper_v1_17.getLine(Paper_v1_17.java:12) ~[CoreProtect-22.0.jar:?]
        at net.coreprotect.listener.player.SignChangeListener.onSignChange(SignChangeListener.java:56) ~[CoreProtect-22.0.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-307]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.updateSignText(ServerGamePacketListenerImpl.java:3580) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleSignUpdate$32(ServerGamePacketListenerImpl.java:3536) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by ostermine** [comment]
more

```
[14:23:41 WARN]: java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 4
[14:23:41 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[14:23:41 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[14:23:41 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[14:23:41 WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:359)
[14:23:41 WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
[14:23:41 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.block.CraftSign.line(CraftSign.java:35)
[14:23:41 WARN]:        at CoreProtect-22.0.jar//net.coreprotect.paper.Paper_v1_17.getLine(Paper_v1_17.java:12)
[14:23:41 WARN]:        at CoreProtect-22.0.jar//net.coreprotect.listener.block.BlockBreakListener.processBlockBreak(BlockBreakListener.java:285)
[14:23:41 WARN]:        at CoreProtect-22.0.jar//net.coreprotect.listener.block.BlockBreakListener.onBlockBreak(BlockBreakListener.java:340)
[14:23:41 WARN]:        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[14:23:41 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[14:23:41 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:23:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
[14:23:41 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:369)
[14:23:41 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:328)
[14:23:41 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:292)
[14:23:41 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1883)
[14:23:41 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:42)
[14:23:41 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:15)
[14:23:41 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[14:23:41 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:23:41 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[14:23:41 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[14:23:41 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[14:23:41 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[14:23:41 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[14:23:41 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[14:23:41 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[14:23:41 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[14:23:41 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1389)
[14:23:41 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1173)
[14:23:41 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[14:23:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by wling-art** [comment]
Yes, I'm having this problem too
I have[ LockettePro](https://www.spigotmc.org/resources/lockettepro-for-1-14-to-1-19.74354/) installed causing this problem, and whenever I take a noticeboard and right click to create a protection it reports this error!
