### ISSUE TITLE
lag + crash

### ISSUE THREAD

**Issue by Link0Darck** [PlayPro/CoreProtect#437]
Good morning,
it keeps lag my server until crash

```
[01:36:28] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to CoreProtect v22.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:416) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:356) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:556) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1640) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1152) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1131) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1124) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1108) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1019) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'boolean org.bukkit.block.Sign.isWaxed()'
        at net.coreprotect.bukkit.Bukkit_v1_20.isWaxed(Bukkit_v1_20.java:134) ~[?:?]
        at net.coreprotect.listener.block.BlockPlaceListener.onBlockPlace(BlockPlaceListener.java:128) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more
[01:38:26] [Server thread/ERROR]: Could not pass event SignChangeEvent to CoreProtect v22.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.block.entity.TileEntitySign.setMessages(TileEntitySign.java:224) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.world.level.block.entity.TileEntitySign.lambda$8(TileEntitySign.java:186) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.world.level.block.entity.TileEntitySign.a(TileEntitySign.java:199) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.world.level.block.entity.TileEntitySign.a(TileEntitySign.java:185) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3005) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.server.network.PlayerConnection.lambda$23(PlayerConnection.java:2986) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1152) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1131) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1124) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1108) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1019) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3801-Spigot-bed8c61-66c5ce4]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'boolean org.bukkit.block.Sign.isWaxed()'
        at net.coreprotect.bukkit.Bukkit_v1_20.isWaxed(Bukkit_v1_20.java:134) ~[?:?]
        at net.coreprotect.listener.player.SignChangeListener.onSignChange(SignChangeListener.java:64) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 24 more
```

**Comment by Intelli** [comment]
Update your server. You're using an unsupported / outdated Spigot build.

**Comment by Link0Darck** [comment]
> Update your server. You're using an unsupported / outdated Spigot build.

minecraft server spigot 1.20.1 how is it already outdated ????

**Comment by Intelli** [comment]
You're using an extremely outdated Spigot 1.20.1 build.

**Comment by Link0Darck** [comment]
> You're using an extremely outdated Spigot 1.20.1 build.

Thank you for the moment it seems to work I will let you know tomorrow when I have more people
