### ISSUE TITLE
[BUG] getGeneratedKeys no longer supported with sqlite-jdbc 3.43.0.0 (MC 1.20.2)

### ISSUE THREAD

**Issue by aspargas2** [PlayPro/CoreProtect#455]
See [this sqlite-jdbc issue](https://github.com/xerial/sqlite-jdbc/issues/329). As of Minecraft 1.20.2, the Spigot and Paper server jars now pull sqlite-jdbc version 3.43.0.0, which no longer supports PreparedStatement.getGeneratedKeys. This causes the following error to appear in the console when an entity is killed (and probably others too, in the less commonly reached codepaths where `getGeneratedKeys` is used):
```
[14:17:30] [Thread-16/WARN]: java.sql.SQLFeatureNotSupportedException: not implemented by SQLite JDBC driver
[14:17:30] [Thread-16/WARN]:    at org.sqlite.jdbc3.JDBC3PreparedStatement.unsupported(JDBC3PreparedStatement.java:448)
[14:17:30] [Thread-16/WARN]:    at org.sqlite.jdbc3.JDBC3Statement.getGeneratedKeys(JDBC3Statement.java:357)
[14:17:30] [Thread-16/WARN]:    at net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:47)
[14:17:30] [Thread-16/WARN]:    at net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[14:17:30] [Thread-16/WARN]:    at net.coreprotect.consumer.process.Process.processConsumer(Process.java:197)
[14:17:30] [Thread-16/WARN]:    at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[14:17:30] [Thread-16/WARN]:    at java.base/java.lang.Thread.run(Thread.java:833)
```
Please let me know if there's any other information I can provide to help this get fixed.

**Comment by JesperKnez** [comment]
[14:11:47] [Thread-8/WARN]: java.sql.SQLFeatureNotSupportedException: not implemented by SQLite JDBC driver

[14:11:47] [Thread-8/WARN]: 	at org.sqlite.jdbc3.JDBC3PreparedStatement.unsupported(JDBC3PreparedStatement.java:448)

[14:11:47] [Thread-8/WARN]: 	at org.sqlite.jdbc3.JDBC3Statement.getGeneratedKeys(JDBC3Statement.java:357)

[14:11:47] [Thread-8/WARN]: 	at CoreProtect-22.1.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:47)

[14:11:47] [Thread-8/WARN]: 	at CoreProtect-22.1.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)

[14:11:47] [Thread-8/WARN]: 	at CoreProtect-22.1.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:197)

[14:11:47] [Thread-8/WARN]: 	at CoreProtect-22.1.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)

[14:11:47] [Thread-8/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)

I'm experiencing this too since i've updated my server to 1.20.2.
