### ISSUE TITLE
Plugin is disabled error

### ISSUE THREAD

**Issue by zhirchik** [PlayPro/CoreProtect#459]
Start server on Mohist 1.19.2
Every time I try to use any command from the plugin, it throws the following error:

null
org.bukkit.command.CommandException: Cannot execute command 'co' in plugin CoreProtect v22.2 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[forge-1.19.2-43.2.18-universal.jar%23150!/:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:160) ~[forge-1.19.2-43.2.18-universal.jar%23150!/:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:799) ~[forge-1.19.2-43.2.18-universal.jar%23150!/:7e29f765-296df566-9fb885e8]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[forge-1.19.2-43.2.18-universal.jar%23150!/:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar%23113!/:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:299) ~[server-1.19.2-20220805.130853-srg.jar%23145!/:?]
        at net.minecraft.commands.Commands.m_242674_(Commands.java:279) ~[server-1.19.2-20220805.130853-srg.jar%23145!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_242600_(ServerGamePacketListenerImpl.java:1335) ~[server-1.19.2-20220805.130853-srg.jar%23145!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$12(ServerGamePacketListenerImpl.java:1313) ~[server-1.19.2-20220805.130853-srg.jar%23145!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:68) ~[server-1.19.2-20220805.130853-srg.jar%23145!/:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.19.2-20220805.130853-srg.jar%23145!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23145!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.19.2-20220805.130853-srg.jar%23145!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:901) ~[server-1.19.2-20220805.130853-srg.jar%23145!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:171) ~[server-1.19.2-20220805.130853-srg.jar%23145!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23145!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:884) ~[server-1.19.2-20220805.130853-srg.jar%23145!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:878) ~[server-1.19.2-20220805.130853-srg.jar%23145!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.19.2-20220805.130853-srg.jar%23145!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:864) ~[server-1.19.2-20220805.130853-srg.jar%23145!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:795) ~[server-1.19.2-20220805.130853-srg.jar%23145!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:278) ~[server-1.19.2-20220805.130853-srg.jar%23145!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by zhirchik** [comment]
I fixed this by updating mohist to a new version
