### ISSUE TITLE
SkullOwner isn't logged

### ISSUE THREAD

**Issue by NedHuman** [PlayPro/CoreProtect#473]
Issue 2# states that skullOwner isnt logged, seems it is closed now. But when I tried it appears SkullOwner still isn't logged

**Comment by Intelli** [comment]
It's logged, but in testing, it sometimes appears to be throwing an error during rollbacks.

Tested placing a player head with the following command: `/give @p minecraft:player_head{SkullOwner:Notch}`

Upon placing, rolling back, and restoring, it initially came back fine. However, upon attempting to repeat the test multiple times, it started throwing the following error:

`[14:46:30 WARN]: java.lang.NullPointerException: Profile name must not be null
[14:46:30 WARN]: 	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
[14:46:30 WARN]: 	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31)
[14:46:30 WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.block.CraftSkull.setOwningPlayer(CraftSkull.java:106)
[14:46:30 WARN]: 	at CoreProtect.jar//net.coreprotect.database.statement.SkullStatement.getData(SkullStatement.java:50)
[14:46:30 WARN]: 	at CoreProtect.jar//net.coreprotect.consumer.process.SkullUpdateProcess.process(SkullUpdateProcess.java:22)
[14:46:30 WARN]: 	at CoreProtect.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:182)
[14:46:30 WARN]: 	at CoreProtect.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[14:46:30 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by NedHuman** [comment]
> It's logged, but in testing, it sometimes appears to be throwing an error during rollbacks.
> 
> Tested placing a player head with the following command: `/give @p minecraft:player_head{SkullOwner:Notch}`
> 
> Upon placing, rolling back, and restoring, it initially came back fine. However, upon attempting to repeat the test multiple times, it started throwing the following error:
> 
> `[14:46:30 WARN]: java.lang.NullPointerException: Profile name must not be null [14:46:30 WARN]: at java.base/java.util.Objects.requireNonNull(Objects.java:233) [14:46:30 WARN]: at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31) [14:46:30 WARN]: at org.bukkit.craftbukkit.v1_20_R2.block.CraftSkull.setOwningPlayer(CraftSkull.java:106) [14:46:30 WARN]: at CoreProtect.jar//net.coreprotect.database.statement.SkullStatement.getData(SkullStatement.java:50) [14:46:30 WARN]: at CoreProtect.jar//net.coreprotect.consumer.process.SkullUpdateProcess.process(SkullUpdateProcess.java:22) [14:46:30 WARN]: at CoreProtect.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:182) [14:46:30 WARN]: at CoreProtect.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133) [14:46:30 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)`

any way for me to view the skullowner in /co i? hovering above it doesn't show
