### ISSUE TITLE
Could not pass event ProjectileLaunchEvent to CoreProtect v22.2 (1.20.6 ?)

### ISSUE THREAD

**Issue by LEMIBANDDEXARI** [PlayPro/CoreProtect#535]
May be a problem with 1.20.6

CoreProtect v22.2
paper.1.20.6-35

I got this when I shot an arrow at a bat
```
[13:41:06 ERROR]: Could not pass event ProjectileLaunchEvent to CoreProtect v22.2
java.lang.NoSuchMethodError: 'org.bukkit.potion.PotionData org.bukkit.entity.Arrow.getBasePotionData()'
        at CoreProtect-22.2.jar/net.coreprotect.listener.PlayerPickupArrowListener.getArrowType(PlayerPickupArrowListener.java:34) ~[CoreProtect-22.2.jar:?]
        at CoreProtect-22.2.jar/net.coreprotect.listener.player.ProjectileLaunchListener.onProjectileLaunch(ProjectileLaunchListener.java:85) ~[CoreProtect-22.2.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:git-Paper-35]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:git-Paper-35]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:git-Paper-35]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callProjectileLaunchEvent(CraftEventFactory.java:1470) ~[paper-1.20.6.jar:git-Paper-35]
        at org.bukkit.craftbukkit.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:698) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1705) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1627) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1622) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.world.item.ProjectileWeaponItem.shoot(ProjectileWeaponItem.java:76) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.world.item.BowItem.releaseUsing(BowItem.java:34) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.world.item.ItemStack.releaseUsing(ItemStack.java:931) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.world.entity.LivingEntity.releaseUsingItem(LivingEntity.java:4061) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1830) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1515) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:198) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1492) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1415) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1607) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-35]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by AmkSoft** [comment]
I got the same, but this time whenn i right clicked on a fencegate using a bow to open it 

`[18:08:26] [Server thread/ERROR]: Could not pass event ProjectileLaunchEvent to CoreProtect v22.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:600) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:587) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R4.event.CraftEventFactory.callProjectileLaunchEvent(CraftEventFactory.java:1290) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at org.bukkit.craftbukkit.v1_20_R4.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:673) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at net.minecraft.server.level.WorldServer.addEntity(WorldServer.java:1103) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at net.minecraft.server.level.WorldServer.addFreshEntity(WorldServer.java:1040) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at net.minecraft.server.level.WorldServer.b(WorldServer.java:1035) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at net.minecraft.world.item.ItemProjectileWeapon.a(ItemProjectileWeapon.java:76) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at net.minecraft.world.item.ItemBow.a(SourceFile:47) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at net.minecraft.world.item.ItemStack.a(ItemStack.java:909) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at net.minecraft.world.entity.EntityLiving.fA(EntityLiving.java:3866) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1502) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:50) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:34) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:162) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1242) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at net.minecraft.util.thread.IAsyncTaskHandler.A(SourceFile:136) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at net.minecraft.server.MinecraftServer.bu(MinecraftServer.java:1221) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at net.minecraft.server.MinecraftServer.A(MinecraftServer.java:1214) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at net.minecraft.util.thread.IAsyncTaskHandler.bA(SourceFile:121) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at net.minecraft.server.MinecraftServer.v_(MinecraftServer.java:1185) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1071) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4137-Spigot-e2c1eee-666f091]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NoSuchMethodError: 'org.bukkit.potion.PotionData org.bukkit.entity.Arrow.getBasePotionData()'
        at net.coreprotect.listener.PlayerPickupArrowListener.getArrowType(PlayerPickupArrowListener.java:34) ~[?:?]
        at net.coreprotect.listener.player.ProjectileLaunchListener.onProjectileLaunch(ProjectileLaunchListener.java:85) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        ... 29 more
[18:08:26] [Server thread/INFO]: Send: Could not pass event PlayerPickupArrowEvent to CoreProtect v22.2
`
