### ISSUE TITLE
Unknown warn

### ISSUE THREAD

**Issue by IdangorI** [PlayPro/CoreProtect#539]
[18:34:51 WARN]: java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because the return value of "java.util.concurrent.ConcurrentHashMap.get(Object)" is null
[18:34:51 WARN]:        at CoreProtect-22.3.jar//net.coreprotect.consumer.process.ContainerTransactionProcess.process(ContainerTransactionProcess.java:49)
[18:34:51 WARN]:        at CoreProtect-22.3.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:152)
[18:34:51 WARN]:        at CoreProtect-22.3.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[18:34:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Intelli** [comment]
Please provide your full log.

**Comment by SiSchu** [comment]
I have the same issue on my server. 
[latest (2).log](https://github.com/PlayPro/CoreProtect/files/15269189/latest.2.log)

**Comment by lerokko** [comment]
Same error as well:
(removed IPs and chat messages)
[latest.log](https://github.com/PlayPro/CoreProtect/files/15283067/latest.log)
