### ISSUE TITLE
Crash randomly

### ISSUE THREAD

**Issue by kaweepatinn1** [PlayPro/CoreProtect#546]
Console logs this before a crash:

[22:54:07] [Thread-17/WARN]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[22:54:07] [Thread-17/WARN]:    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:579)
[22:54:07] [Thread-17/WARN]:    at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:84)
[22:54:07] [Thread-17/WARN]:    at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[22:54:07] [Thread-17/WARN]:    at net.coreprotect.consumer.process.Process.processConsumer(Process.java:148)
[22:54:07] [Thread-17/WARN]:    at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[22:54:07] [Thread-17/WARN]:    at java.base/java.lang.Thread.run(Thread.java:1583)

This is the crash report: 
[crash-2024-05-18_22.54.06-server.txt](https://github.com/PlayPro/CoreProtect/files/15365761/crash-2024-05-18_22.54.06-server.txt)

**Comment by kaweepatinn1** [comment]
Looks like the crash is related to the GSit plugin, server crashed once while getting out of a boat with GSit players on my head. Looks like trying to record multiple players doing one thing together causes the error.

**Comment by Intelli** [comment]
Please provide the full server log, which includes that error message.
