### ISSUE TITLE
Could not pass event InventoryMoveItemEvent to CoreProtect

### ISSUE THREAD

**Issue by Wildhooray** [PlayPro/CoreProtect#549]
This error is repeating always when a players in online.
When I updated to v22.4
I am using spigot 1.20.6-R0.1 snapshot
```
[20:42:08 ERROR]: Could not pass event InventoryMoveItemEvent to CoreProtect v22.4
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:600) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:587) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.block.entity.TileEntityHopper.a(TileEntityHopper.java:235) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]
	at net.minecraft.world.level.block.entity.TileEntityHopper.a(TileEntityHopper.java:171) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]
	at net.minecraft.world.level.block.entity.TileEntityHopper.a(TileEntityHopper.java:152) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]
	at net.minecraft.world.level.chunk.Chunk$a.a(Chunk.java:887) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]
	at net.minecraft.world.level.chunk.Chunk$d.a(Chunk.java:839) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]
	at net.minecraft.world.level.World.T(World.java:666) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:467) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1444) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:402) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1293) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1064) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException
```
This fills up my consal so I can't check the history

**Comment by TheFairyTale** [comment]
Same issue on CatServer 1.16.5 build 69069a9c at my forge 36.2.39, 100 mods server:
```
[09:33:48] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to CoreProtect v22.4
 org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[forge:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:593) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:578) ~[forge:?]
        at net.minecraft.tileentity.HopperTileEntity.func_145883_k(HopperTileEntity.java:213) ~[?:?]
        at net.minecraft.tileentity.HopperTileEntity.func_200109_a(HopperTileEntity.java:156) ~[?:?]
        at net.minecraft.tileentity.HopperTileEntity.func_73660_a(HopperTileEntity.java:139) ~[?:?]
        at net.minecraft.world.World.func_217391_K(World.java:696) ~[?:?]
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:506) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1049) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:336) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:943) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:775) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NullPointerException
```

**Comment by LilithASMP** [comment]
![image](https://github.com/PlayPro/CoreProtect/assets/170349783/4b3f4fed-31e1-4ae0-a94f-90f82d933113)

**Comment by MarkPaj** [comment]
Hi, Same issue on Spigot 1.20.6:
`[21:15:56] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to CoreProtect v22.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.block.entity.TileEntityHopper.a(TileEntityHopper.java:235) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4184-Spigot-fcd94e2-16c9767]
        at net.minecraft.world.level.block.entity.TileEntityHopper.a(TileEntityHopper.java:171) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4184-Spigot-fcd94e2-16c9767]
        at net.minecraft.world.level.block.entity.TileEntityHopper.a(TileEntityHopper.java:152) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4184-Spigot-fcd94e2-16c9767]
        at net.minecraft.world.level.chunk.Chunk$a.a(Chunk.java:887) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4184-Spigot-fcd94e2-16c9767]
        at net.minecraft.world.level.chunk.Chunk$d.a(Chunk.java:839) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4184-Spigot-fcd94e2-16c9767]
        at net.minecraft.world.level.World.T(World.java:666) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4184-Spigot-fcd94e2-16c9767]
        at net.minecraft.server.level.WorldServer.a(WorldServer.java:467) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4184-Spigot-fcd94e2-16c9767]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1444) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4184-Spigot-fcd94e2-16c9767]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:402) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4184-Spigot-fcd94e2-16c9767]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1293) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4184-Spigot-fcd94e2-16c9767]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1064) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4184-Spigot-fcd94e2-16c9767]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4184-Spigot-fcd94e2-16c9767]
        at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException`

**Comment by Plackett** [comment]
![image](https://github.com/PlayPro/CoreProtect/assets/80919085/4044424e-5fe7-4176-b470-9d07e5df8d8b)
Same issue on Spigot 1.21

**Comment by NOIR-DexPrkr** [comment]
Same here, same console spam issue. Paper 1.18.2

**Comment by Intelli** [comment]
Already fixed here: https://github.com/PlayPro/CoreProtect/commit/cfb53f766e9fcc661b6c26d118e3566c6c07334c

**Comment by TheKrimes** [comment]
brother in aternos its not working i tried to run it on the latest 22.4 version but its still giving the same error. Help me out here brother, i expect a response from you pls pls

**Comment by Skullians** [comment]
Fixed in v23 @TheKrimes 
Unsure if aternos will have it because it's on patreon free tier.
Move away from aternos if you can, move to fps.ms or mcho.st. They give you full control over files

**Comment by TheKrimes** [comment]
I also tried on V22.3 too and the same error happened, so now I am testing on V22.0, yes but aternos is free no we don't have money right now.

**Comment by TheKrimes** [comment]
> v22.3???
> that's an older version than 22.4

YES, tried both on V22.3 and V22.4 but now I am running V22.0 as in older versions we don't used to get this error and it's working though no errors in V22.0. Btw can you tell me why is this error happening ??

**Comment by Skullians** [comment]
If you actually read, this was fixed on VERSION 23.
**NOT** 22.3, **NOT** 22.4

**Comment by Skullians** [comment]
Also, mcho.st and fps.ms are free hosts

**Comment by TheKrimes** [comment]
> If you actually read, this was fixed on VERSION 23.
> **NOT** 22.3, **NOT** 22.4

Ohh my bad sorry I thought it was a mistype

**Comment by TheKrimes** [comment]
> Also, mcho.st and fps.ms are free hosts

Definitely I will check mcho.st out but fps.ms is not available in my country btw can you tell me why this error happens ??

**Comment by Skullians** [comment]
your region is probably blocked
