### ISSUE TITLE
Console spam on PlayerDeathEvent

### ISSUE THREAD

**Issue by Cozary** [PlayPro/CoreProtect#557]
CoreProtect v22.4
Paper v1.20.6-138

```
 Could not pass event PlayerDeathEvent to CoreProtect v22.4
java.lang.NullPointerException: null
        at io.papermc.paper.util.TransformingRandomAccessList$1.transform(TransformingRandomAccessList.java:64) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-138-906df69]
        at io.papermc.paper.util.TransformingRandomAccessList$TransformedListIterator.next(TransformingRandomAccessList.java:161) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-138-906df69]
        at CoreProtect-22.4.jar/net.coreprotect.listener.player.PlayerDeathListener.onPlayerDeath(PlayerDeathListener.java:41) ~[CoreProtect-22.4.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-138-906df69]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:1020) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:1046) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1584) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:986) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1213) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.world.entity.LivingEntity.causeFallDamage(LivingEntity.java:2095) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.world.entity.player.Player.causeFallDamage(Player.java:1731) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.world.level.block.Block.fallOn(Block.java:460) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.world.entity.Entity.checkFallDamage(Entity.java:1846) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.world.entity.LivingEntity.checkFallDamage(LivingEntity.java:394) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.level.ServerPlayer.doCheckFallDamage(ServerPlayer.java:1625) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1596) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:34) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:105) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Cozary** [comment]
The problem was due to using another plugin (IronicChest) that was outdated. Sorry.
