### ISSUE TITLE
What should I do for a mistake?

### ISSUE THREAD

**Issue by BAD7777** [PlayPro/CoreProtect#569]
[18:57:33 WARN]: java.sql.BatchUpdateException: Data truncation: Data too long for column 'data' at row 3
[18:57:33 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:223)
[18:57:33 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchWithMultiValuesClause(ClientPreparedStatement.java:716)
[18:57:33 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:407)
[18:57:33 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:802)
[18:57:33 WARN]:        at CoreProtect-22.4 (1).jar//net.coreprotect.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
[18:57:33 WARN]:        at CoreProtect-22.4 (1).jar//net.coreprotect.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
[18:57:33 WARN]:        at CoreProtect-22.4 (1).jar//net.coreprotect.consumer.process.Process.commit(Process.java:295)
[18:57:33 WARN]:        at CoreProtect-22.4 (1).jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:257)
[18:57:33 WARN]:        at CoreProtect-22.4 (1).jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[18:57:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[18:57:33 WARN]: Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'data' at row 3
[18:57:33 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
[18:57:33 WARN]:        at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:555)
[18:57:33 WARN]:        at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:339)
[18:57:33 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1054)
[18:57:33 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1003)
[18:57:33 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1312)
[18:57:33 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchWithMultiValuesClause(ClientPreparedStatement.java:677)
[18:57:33 WARN]:        ... 8 more

**Comment by Intelli** [comment]
Please post your full log.
