### ISSUE TITLE
为什么当一个玩家打破方块是，服务器后台几乎每一秒有大量不间断的报错（直到关闭服务器）

### ISSUE THREAD

**Issue by Ling-shi2011** [PlayPro/CoreProtect#572]
报错如下
[21:34:23] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to CoreProtect v22.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.block.entity.TileEntityHopper.a(TileEntityHopper.java:235) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.world.level.block.entity.TileEntityHopper.a(TileEntityHopper.java:171) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.world.level.block.entity.TileEntityHopper.a(TileEntityHopper.java:152) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.world.level.chunk.Chunk$a.a(Chunk.java:899) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.world.level.chunk.Chunk$d.a(Chunk.java:851) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.world.level.World.T(World.java:671) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.level.WorldServer.a(WorldServer.java:468) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1472) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.dedicated.DedicatedServer.c(DedicatedServer.java:406) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1321) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1071) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getBlockX()" because "destinationLocation" is null
        at net.coreprotect.listener.player.HopperPushListener.processHopperPush(HopperPushListener.java:23) ~[?:?]
        at net.coreprotect.listener.player.InventoryChangeListener.onInventoryMoveItemEvent(InventoryChangeListener.java:345) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        ... 16 more

**Comment by xiao-k233** [comment]
建议改成英文

**Comment by YuanYuanOwO** [comment]
理论上应该是下个版本修复，但你也可以自己构建一份 CoreProtect Jar文件

**Comment by Mraz777** [comment]
我也是，估计强行用老版本插件装1.21服务器导致的，但也没有其他回档插件用了，不知道作者什么时候更新1.21，太难了

**Comment by xiao-k233** [comment]
已经更新了，就是不知道怎么在配置文件改分支，我在代码写死的，硬编码手动改



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月27日(周四) 晚上11:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PlayPro/CoreProtect] 为什么当一个玩家打破方块是，服务器后台几乎每一秒有大量不间断的报错（直到关闭服务器） (Issue #572)




 
我也是，估计强行用老版本插件装1.21服务器导致的，但也没有其他回档插件用了，不知道作者什么时候更新1.21，太难了

**Comment by Mraz777** [comment]
@xiao-k233 大佬可以分享下更新后的jar文件吗，我不懂编程，不知道怎么构建jar

**Comment by Intelli** [comment]
Fixed here: https://github.com/PlayPro/CoreProtect/commit/cfb53f766e9fcc661b6c26d118e3566c6c07334c
