### ISSUE TITLE
NPE warning when interacting with food items with custom components (without them actually going into a container block)

### ISSUE THREAD

**Issue by CyberFlameGO** [PlayPro/CoreProtect#573]
Ignore the random blank lines and prepended "!" characters - shamelessly copied straight from DiscordSRV. Tested on `Purpur Version: 1.21-2247-39617d5 (MC: 1.21)*` with build from [ce8c194](https://github.com/PlayPro/CoreProtect/commit/ce8c194e0dbcc1b5e7a7a4b7c9d78e8c3ede5c6f) 
```diff
! [Thu 00:28:29 WARN ] java.lang.NullPointerException: null value in entry: using-converts-to=null
! [Thu 00:28:29 WARN ]     at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33)
! [Thu 00:28:29 WARN ]     at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:54)
! [Thu 00:28:29 WARN ]     at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:341)
! [Thu 00:28:29 WARN ]     at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:450)
! [Thu 00:28:29 WARN ]     at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:465)
! [Thu 00:28:29 WARN ]     at com.google.common.collect.ImmutableMap$Builder.putAll(ImmutableMap.java:494)
! [Thu 00:28:29 WARN ]     at com.google.common.collect.ImmutableMap$Builder.putAll(ImmutableMap.java:477)
! [Thu 00:28:29 WARN ]     at org.bukkit.util.io.Wrapper.newWrapper(Wrapper.java:16)
! [Thu 00:28:29 WARN ]     at org.bukkit.util.io.BukkitObjectOutputStream.replaceObject(BukkitObjectOutputStream.java:48)
 
! [Thu 00:28:29 WARN ]     at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1160)
! [Thu 00:28:29 WARN ]     at java.base/java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1394)
! [Thu 00:28:29 WARN ]     at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1190)
! [Thu 00:28:29 WARN ]     at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1585)
! [Thu 00:28:29 WARN ]     at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1542)
! [Thu 00:28:29 WARN ]     at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
! [Thu 00:28:29 WARN ]     at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
! [Thu 00:28:29 WARN ]     at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
! [Thu 00:28:29 WARN ]     at java.base/java.util.ArrayList.writeObject(ArrayList.java:949)
! [Thu 00:28:29 WARN ]     at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
! [Thu 00:28:29 WARN ]     at java.base/java.lang.reflect.Method.invoke(Method.java:580)
! [Thu 00:28:29 WARN ]     at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1078)
! [Thu 00:28:29 WARN ]     at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
! [Thu 00:28:29 WARN ]     at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
! [Thu 00:28:29 WARN ]     at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
! [Thu 00:28:29 WARN ]     at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
! [Thu 00:28:29 WARN ]     at java.base/java.util.ArrayList.writeObject(ArrayList.java:949)
! [Thu 00:28:29 WARN ]     at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
! [Thu 00:28:29 WARN ]     at java.base/java.lang.reflect.Method.invoke(Method.java:580)
! [Thu 00:28:29 WARN ]     at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1078)
! [Thu 00:28:29 WARN ]     at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
! [Thu 00:28:29 WARN ]     at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
! [Thu 00:28:29 WARN ]     at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
! [Thu 00:28:29 WARN ]     at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
! [Thu 00:28:29 WARN ]     at CoreProtect-22.4.jar//net.coreprotect.utility.Util.convertByteData(Util.java:576)
! [Thu 00:28:29 WARN ]     at CoreProtect-22.4.jar//net.coreprotect.database.statement.ItemStatement.insert(ItemStatement.java:15)
! [Thu 00:28:29 WARN ]     at CoreProtect-22.4.jar//net.coreprotect.database.logger.ItemLogger.logTransaction(ItemLogger.java:145)
! [Thu 00:28:29 WARN ]     at CoreProtect-22.4.jar//net.coreprotect.database.logger.ContainerLogger.log(ContainerLogger.java:147)
! [Thu 00:28:29 WARN ]     at CoreProtect-22.4.jar//net.coreprotect.consumer.process.ContainerTransactionProcess.process(ContainerTransactionProcess.java:42)
! [Thu 00:28:29 WARN ]     at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:160)
! [Thu 00:28:29 WARN ]     at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
! [Thu 00:28:29 WARN ]     at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by Intelli** [comment]
Please provide steps to replicate.

**Comment by CyberFlameGO** [comment]
Interacting with the item produced by this command in your inventory should
be sufficient to repro the warn:

minecraft:give @a minecraft:burn_pottery_sherd[food={nutrition:0,
saturation:0, eat_seconds:0.1, can_always_eat:true},
item_name="{'italic':false,'text':'munch this RIGHT
NOW!!!','bold':true}",lore=["{'text':'do it'}"]] 64

**Comment by Intelli** [comment]
What do you mean by interacting?

**Comment by CyberFlameGO** [comment]
One of these (I don't remember and cannot test for at least three days 😭)
- using the item, holding it, or moving it around the inventory

**Comment by Intelli** [comment]
Unable to replicate the issue being described.

(NullPointerException is replicable, but only in expected situations, such as when inserting the item in a container)

**Comment by CyberFlameGO** [comment]
Hmm - in the case of expected situations would that be able to get
resolved? I'd assume if it boils down to the same erroneous code the fix
would apply to my encounter of it (perhaps)

**Comment by Intelli** [comment]
Please test again and provide additional information once you're able to replicate the issue.

**Comment by Laukage** [comment]
I have the same exact error: https://pastebin.com/N9wisLqB

![image](https://github.com/user-attachments/assets/8f919840-f669-4037-9d9b-925cafaad747)
![image](https://github.com/user-attachments/assets/0a8ebb05-c746-4540-b2bf-271bb1197acb)

**Comment by TheAmazingAnimal** [comment]
![image](https://github.com/user-attachments/assets/296ac9be-a14b-4ef0-add6-443f2ab79fb3)
Same problem. 
![image](https://github.com/user-attachments/assets/6b8a4864-ff86-483a-9a61-32d4a446a59b)

**Comment by CyberFlameGO** [comment]
No longer replicable on Purpur 1.21.1-2289-201e928 weirdly
