### ISSUE TITLE
CoreProtect frequently report error 

### ISSUE THREAD

**Issue by Sinora-S** [PlayPro/CoreProtect#574]
When constructing a bone meal production machine in the game,I found the bug.
When items are in the hopper above a composter,CoreProtect frequently report errors.
**MC server core:Spigot1.20.1
MC version:1.20.1
Java version:22**

The specific error message is as follows

>[19:17:42] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to CoreProtect v22.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.block.entity.TileEntityHopper.ejectItems(TileEntityHopper.java:230) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.world.level.block.entity.TileEntityHopper.a(TileEntityHopper.java:166) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.world.level.block.entity.TileEntityHopper.a(TileEntityHopper.java:147) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.world.level.chunk.Chunk$a.a(Chunk.java:889) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.world.level.chunk.Chunk$d.a(Chunk.java:841) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.world.level.World.P(World.java:669) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.level.WorldServer.a(WorldServer.java:452) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1301) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:387) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1014) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException

**Comment by Wqrld** [comment]
Hi,

We can reproduce this on 1.21:
```
[21:09:26] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to CoreProtect v22.4
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
at net.minecraft.world.level.block.entity.TileEntityHopper.a(TileEntityHopper.java:235) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4235-Spigot-cb8cf80-ab29122]
at net.minecraft.world.level.block.entity.TileEntityHopper.a(TileEntityHopper.java:171) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4235-Spigot-cb8cf80-ab29122]
at net.minecraft.world.level.block.entity.TileEntityHopper.a(TileEntityHopper.java:152) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4235-Spigot-cb8cf80-ab29122]
at net.minecraft.world.level.chunk.Chunk$a.a(Chunk.java:899) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4235-Spigot-cb8cf80-ab29122]
at net.minecraft.world.level.chunk.Chunk$d.a(Chunk.java:851) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4235-Spigot-cb8cf80-ab29122]
at net.minecraft.world.level.World.T(World.java:671) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4235-Spigot-cb8cf80-ab29122]
at net.minecraft.server.level.WorldServer.a(WorldServer.java:468) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4235-Spigot-cb8cf80-ab29122]
at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1472) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4235-Spigot-cb8cf80-ab29122]
at net.minecraft.server.dedicated.DedicatedServer.c(DedicatedServer.java:406) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4235-Spigot-cb8cf80-ab29122]
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1321) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4235-Spigot-cb8cf80-ab29122]
at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1071) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4235-Spigot-cb8cf80-ab29122]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4235-Spigot-cb8cf80-ab29122]
at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException
```

**Comment by Intelli** [comment]
Duplicate issue / already fixed in CoreProtect v23

https://github.com/PlayPro/CoreProtect/commit/cfb53f766e9fcc661b6c26d118e3566c6c07334c

**Comment by Sinora-S** [comment]
> 重复问题/已在 CoreProtect v23 中修复
> 
> [CFB53F7系列](https://github.com/PlayPro/CoreProtect/commit/cfb53f766e9fcc661b6c26d118e3566c6c07334c)

When the v23 will release?
