### ISSUE TITLE
The warning keeps repeating on my console,never stop.spigot1.21,jdk21

### ISSUE THREAD

**Issue by Mraz777** [PlayPro/CoreProtect#577]
The console suddenly popped up a few warnings,and then kept repeating this warning:
[Craft Scheduler Thread - 3335/WARN]: java.lang.NullPointerException.
keep repeating this sentence,can't stop.But my server is playing normally.Just the console keeps warning.
I noticed that there is the word coreprotect in the second warning.Is this plugin causing the problem?
spigot1.21....jdk21......

[23:42:34] [Craft Scheduler Thread - 3332/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getWorld()" because "destinationLocation" is null
[23:42:34] [Craft Scheduler Thread - 3332/WARN]:     at net.coreprotect.listener.player.HopperPullListener.lambda$processHopperPull$1(HopperPullListener.java:73)
[23:42:34] [Craft Scheduler Thread - 3332/WARN]:     at org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftTask.run(CraftTask.java:82)
[23:42:34] [Craft Scheduler Thread - 3332/WARN]:     at org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[23:42:34] [Craft Scheduler Thread - 3332/WARN]:     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[23:42:34] [Craft Scheduler Thread - 3332/WARN]:     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[23:42:34] [Craft Scheduler Thread - 3332/WARN]:     at java.base/java.lang.Thread.run(Thread.java:1583)
[23:42:35] [Craft Scheduler Thread - 3335/WARN]: java.lang.NullPointerException
[23:42:35] [Craft Scheduler Thread - 3335/WARN]: java.lang.NullPointerException
[23:42:35] [Craft Scheduler Thread - 3349/WARN]: java.lang.NullPointerException
[23:42:35] [Craft Scheduler Thread - 3357/WARN]: java.lang.NullPointerException
[23:42:35] [Craft Scheduler Thread - 3354/WARN]: java.lang.NullPointerException
[23:42:36] [Craft Scheduler Thread - 3342/WARN]: java.lang.NullPointerException
[23:42:36] [Craft Scheduler Thread - 3332/WARN]: java.lang.NullPointerException

**Comment by Intelli** [comment]
Duplicate issue / already fixed in CoreProtect v23
