### ISSUE TITLE
EntityKillLogger exception when killing villager on 1.21

### ISSUE THREAD

**Issue by Kadeluxe** [PlayPro/CoreProtect#589]
Compiled from latest source and tested on Paper 1.21:

```
[16:51:19 WARN]: java.io.NotSerializableException: org.bukkit.craftbukkit.entity.CraftVillager$CraftProfession
[16:51:19 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1200)
[16:51:19 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[16:51:19 WARN]:        at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[16:51:19 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[16:51:19 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[16:51:19 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[16:51:19 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[16:51:19 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[16:51:19 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[16:51:19 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[16:51:19 WARN]:        at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[16:51:19 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[16:51:19 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[16:51:19 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[16:51:19 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[16:51:19 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[16:51:19 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[16:51:19 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[16:51:19 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:28)
[16:51:19 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:50)
[16:51:19 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[16:51:19 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[16:51:19 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[16:51:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[16:51:19 WARN]: java.sql.SQLException: Illegal operation on empty result set.
[16:51:19 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
[16:51:19 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[16:51:19 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:81)
[16:51:19 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:55)
[16:51:19 WARN]:        at com.mysql.cj.jdbc.result.ResultSetImpl.checkRowPos(ResultSetImpl.java:519)
[16:51:19 WARN]:        at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1252)
[16:51:19 WARN]:        at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:818)
[16:51:19 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.hikari.pool.HikariProxyResultSet.getInt(HikariProxyResultSet.java)
[16:51:19 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:59)
[16:51:19 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[16:51:19 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[16:51:19 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[16:51:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by Kadeluxe** [comment]
Happens with cats too, maybe others mobs as well

**Comment by foxya27** [comment]
I have this problem too
