### ISSUE TITLE
CoreProtect-Edge v23.0-RC3  Console Error

### ISSUE THREAD

**Issue by CatBang** [PlayPro/CoreProtect#591]
1.21： https://mclo.gs/iV3MLZr
1.20.6： https://mclo.gs/Gyb3bxP
My testing on Windows 11 does not seem to produce any errors.

Ubuntu22.04.4
Linux kernel 6.5.0

1.21&1.20.6
My previous version of CoreProtect-Edge was 22.6, and it did not produce any error messages.

**Comment by CatBang** [comment]
CoreProtect-Edge v23.0 still has this WARN message.

**Comment by Rasgnarok** [comment]
Crashing with a lib error on RC3 Core-Protect Edge and v23 Core-Protect Edge. No issues with previous recent builds, including RC2 Core-Protect Edge.

```
[07Aug2024 01:19:39.715] [Server thread/INFO] [CoreProtect/]: Enabling CoreProtect v23.0
[07Aug2024 01:19:39.762] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling CoreProtect v23.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sun/jna/Library
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoaderMixin.java:644) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoaderMixin.java:104) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoaderMixin.java:99) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at com.profesorfalken.jsensors.manager.unix.UnixSensorsManager.loadDynamicLibrary(UnixSensorsManager.java:77) ~[?:?]
	at com.profesorfalken.jsensors.manager.unix.UnixSensorsManager.getSensorsData(UnixSensorsManager.java:50) ~[?:?]
	at com.profesorfalken.jsensors.manager.SensorsManager.getComponents(SensorsManager.java:51) ~[?:?]
	at com.profesorfalken.jsensors.SensorsLocator.getComponents(SensorsLocator.java:34) ~[?:?]
	at com.profesorfalken.jsensors.JSensors.components(JSensors.java:94) ~[?:?]
	at org.jutils.jhardware.util.TemperatureUtils.getCpuTemperatureByjSensors(TemperatureUtils.java:41) ~[?:?]
	at org.jutils.jhardware.util.TemperatureUtils.getCpuTemperatureForLinux(TemperatureUtils.java:92) ~[?:?]
	at org.jutils.jhardware.info.processor.unix.UnixProcessorInfo.parseInfo(UnixProcessorInfo.java:53) ~[?:?]
	at org.jutils.jhardware.info.processor.AbstractProcessorInfo.getInfo(AbstractProcessorInfo.java:29) ~[?:?]
	at org.jutils.jhardware.info.processor.AbstractProcessorInfo.getInfo(AbstractProcessorInfo.java:25) ~[?:?]
	at org.jutils.jhardware.HardwareInfo.getProcessorInfo(HardwareInfo.java:52) ~[?:?]
	at net.coreprotect.utility.Util.getProcessorInfo(Util.java:123) ~[?:?]
	at net.coreprotect.config.ConfigHandler.<clinit>(ConfigHandler.java:59) ~[?:?]
	at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:61) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:263) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServerMixin.java:492) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServerMixin.java:406) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at net.minecraft.server.MinecraftServer.handler$bah000$arclight$enablePlugins(MinecraftServerMixin.java:1995) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServerMixin.java:382) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServerMixin.java:308) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:168) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1879) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.ClassNotFoundException: com.sun.jna.Library
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoaderMixin.java:140) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoaderMixin.java:99) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 34 more
```

```
[07Aug2024 02:28:14.504] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling CoreProtect v23.0-RC3 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sun/jna/Library
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoaderMixin.java:644) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoaderMixin.java:104) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoaderMixin.java:99) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at com.profesorfalken.jsensors.manager.unix.UnixSensorsManager.loadDynamicLibrary(UnixSensorsManager.java:77) ~[?:?]
	at com.profesorfalken.jsensors.manager.unix.UnixSensorsManager.getSensorsData(UnixSensorsManager.java:50) ~[?:?]
	at com.profesorfalken.jsensors.manager.SensorsManager.getComponents(SensorsManager.java:51) ~[?:?]
	at com.profesorfalken.jsensors.SensorsLocator.getComponents(SensorsLocator.java:34) ~[?:?]
	at com.profesorfalken.jsensors.JSensors.components(JSensors.java:94) ~[?:?]
	at org.jutils.jhardware.util.TemperatureUtils.getCpuTemperatureByjSensors(TemperatureUtils.java:41) ~[?:?]
	at org.jutils.jhardware.util.TemperatureUtils.getCpuTemperatureForLinux(TemperatureUtils.java:92) ~[?:?]
	at org.jutils.jhardware.info.processor.unix.UnixProcessorInfo.parseInfo(UnixProcessorInfo.java:53) ~[?:?]
	at org.jutils.jhardware.info.processor.AbstractProcessorInfo.getInfo(AbstractProcessorInfo.java:29) ~[?:?]
	at org.jutils.jhardware.info.processor.AbstractProcessorInfo.getInfo(AbstractProcessorInfo.java:25) ~[?:?]
	at org.jutils.jhardware.HardwareInfo.getProcessorInfo(HardwareInfo.java:52) ~[?:?]
	at net.coreprotect.utility.Util.getProcessorInfo(Util.java:123) ~[?:?]
	at net.coreprotect.config.ConfigHandler.<clinit>(ConfigHandler.java:59) ~[?:?]
	at net.coreprotect.CoreProtect.onEnable(CoreProtect.java:61) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:263) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServerMixin.java:492) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServerMixin.java:406) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at net.minecraft.server.MinecraftServer.handler$bah000$arclight$enablePlugins(MinecraftServerMixin.java:1995) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServerMixin.java:382) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServerMixin.java:308) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:168) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1879) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.ClassNotFoundException: com.sun.jna.Library
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoaderMixin.java:140) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoaderMixin.java:99) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 34 more
```
