### ISSUE TITLE
SQLITE WARN

### ISSUE THREAD

**Issue by IdangorI** [PlayPro/CoreProtect#595]
```
[01:11:52 WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table co_skull has no column named skin)
[01:11:52 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1179)
[01:11:52 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1190)
[01:11:52 WARN]:        at org.sqlite.core.DB.throwex(DB.java:1150)
[01:11:52 WARN]:        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[01:11:52 WARN]:        at org.sqlite.core.NativeDB.prepare(NativeDB.java:132)
[01:11:52 WARN]:        at org.sqlite.core.DB.prepare(DB.java:264)
[01:11:52 WARN]:        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:46)
[01:11:52 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:32)
[01:11:52 WARN]:        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
[01:11:52 WARN]:        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:34)
[01:11:52 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:225)
[01:11:52 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
[01:11:52 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.Database.prepareStatement(Database.java:294)
[01:11:52 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.Database.prepareStatement(Database.java:245)
[01:11:52 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:112)
[01:11:52 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[01:11:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[01:11:52 WARN]: java.lang.NullPointerException: Cannot invoke "java.sql.PreparedStatement.executeBatch()" because "preparedStmtSkulls" is null
[01:11:52 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.commit(Process.java:293)
[01:11:52 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:257)
[01:11:52 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[01:11:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[01:11:52 WARN]: java.lang.NullPointerException: Cannot invoke "java.sql.PreparedStatement.close()" because "preparedStmtSkulls" is null
[01:11:52 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:262)
[01:11:52 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[01:11:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Despite the fact that this is a warning, new data is not written to the database. A warning appears from one or more players, there are no warnings on an empty server.** 

[fda87e2](https://github.com/PlayPro/CoreProtect/commit/fda87e2f6ae4eaa1205fcb520a7e68be0cb553ac) development build

**Comment by Intelli** [comment]
Manual compilation issue. You can resolve this by either resetting your database or using the pre-built file on Patreon.

**Comment by fucksophie** [comment]
What's the manual compliation issue?

**Comment by ScuroK** [comment]
i have the same problem. what does "manual compilation issue" mean??

**Comment by Skullians** [comment]
In updates of CoreProtect the structure of the database tables change.
iirc, Patron jar releases automatically update the tables, however if you compile it yourself you have to figure it out yourself.
See https://github.com/PlayPro/CoreProtect/tree/master/src/main/java/net/coreprotect/patch and https://github.com/PlayPro/CoreProtect/blob/master/src/main/java/net/coreprotect/patch/script/__2_23_0.java / https://github.com/PlayPro/CoreProtect/blob/master/src/main/java/net/coreprotect/patch/script/__2_23_1.java

**Comment by ScuroK** [comment]
boahr i wish co would just become a normal premium resource on spigot. i would pay even a high price. but i dont want to use patreon and pay for every update :S
