### ISSUE TITLE
Warning NotSerializableException in CraftVillager$CraftProfession

### ISSUE THREAD

**Issue by gaetanse** [PlayPro/CoreProtect#596]
Hi, i just have a warning in my log :

```
[02:29:46 WARN]: java.io.NotSerializableException: org.bukkit.craftbukkit.entity.CraftVillager$CraftProfession
[02:29:46 WARN]: at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1200)
[02:29:46 WARN]: at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[02:29:46 WARN]: at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[02:29:46 WARN]: at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[02:29:46 WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[02:29:46 WARN]: at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[02:29:46 WARN]: at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[02:29:46 WARN]: at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[02:29:46 WARN]: at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[02:29:46 WARN]: at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[02:29:46 WARN]: at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[02:29:46 WARN]: at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[02:29:46 WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[02:29:46 WARN]: at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[02:29:46 WARN]: at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[02:29:46 WARN]: at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[02:29:46 WARN]: at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[02:29:46 WARN]: at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[02:29:46 WARN]: at CoreProtect-22.4.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:27)
[02:29:46 WARN]: at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:49)
[02:29:46 WARN]: at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[02:29:46 WARN]: at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[02:29:46 WARN]: at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[02:29:46 WARN]: at java.base/java.lang.Thread.run(Thread.java:1583)
[02:29:46 WARN]: java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.next()" because "resultSet" is null
[02:29:46 WARN]: at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:51)
[02:29:46 WARN]: at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[02:29:46 WARN]: at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[02:29:46 WARN]: at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[02:29:46 WARN]: at java.base/java.lang.Thread.run(Thread.java:1583)
```

For information i have use all of this : 

Plugins:
FancyHolograms, AntiCreeper, ATopPlayers, CoreProtect, dynmap, Dynmap-GriefPrevention, Essentials, EssentialsChat, EssentialsSpawn, GriefPrevention, LoginSecurity, LuckPerms, Maintenance, SkinsRestorer, Vault

Using paper-1.21-109

**Comment by Skullians** [comment]
You are using an outdated version of CoreProtect, v23 solves this issue.
To currently get v23, you must either be a Patron or you can compile the plugin manually through the GitHub for free.

**Comment by gaetanse** [comment]
Thanks for the answer
