### ISSUE TITLE
NullPointerException message when villager dies.

### ISSUE THREAD

**Issue by itscola** [PlayPro/CoreProtect#605]
```
[18:38:16 INFO]: Villager Villager['Shepherd'/178494, uuid='9c61a3f8-876a-41df-b2e3-1aaf2c270e67', l='ServerLevel[world]', x=-18221.38, y=122.00, z=14653.62, cpos=[-1139, 915], tl=440998, v=true] died, message: 'Shepherd was slain by ... ]'
[18:38:16 WARN]: java.io.NotSerializableException: org.bukkit.craftbukkit.entity.CraftVillager$CraftProfession
[18:38:16 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1200)
[18:38:16 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[18:38:16 WARN]:        at java.base/java.util.ArrayList.writeObject(ArrayList.java:949)
[18:38:16 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:38:16 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[18:38:16 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1078)
[18:38:16 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[18:38:16 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[18:38:16 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[18:38:16 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[18:38:16 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:27)
[18:38:16 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:49)
[18:38:16 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[18:38:16 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[18:38:16 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[18:38:16 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
[18:38:16 WARN]: java.lang.NullPointerException
```

**Comment by Skullians** [comment]
https://github.com/PlayPro/CoreProtect/issues/600#issuecomment-2265229174
