### ISSUE TITLE
console spam

### ISSUE THREAD

**Issue by W07M0** [PlayPro/CoreProtect#607]
[18:52:11 WARN]: java.io.NotSerializableException: org.bukkit.craftbukkit.entity.CraftVillager$CraftProfession
[18:52:11 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1200)
[18:52:11 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[18:52:11 WARN]:        at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[18:52:11 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:52:11 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[18:52:11 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[18:52:11 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[18:52:11 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[18:52:11 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[18:52:11 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[18:52:11 WARN]:        at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[18:52:11 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:52:11 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[18:52:11 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[18:52:11 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[18:52:11 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[18:52:11 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[18:52:11 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[18:52:11 WARN]:        at CoreProtect-Edge-23.0-rc1.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:28)
[18:52:11 WARN]:        at CoreProtect-Edge-23.0-rc1.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:49)
[18:52:11 WARN]:        at CoreProtect-Edge-23.0-rc1.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[18:52:11 WARN]:        at CoreProtect-Edge-23.0-rc1.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[18:52:11 WARN]:        at CoreProtect-Edge-23.0-rc1.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[18:52:11 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[18:52:11 WARN]: java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.next()" because "resultSet" is null
[18:52:11 WARN]:        at CoreProtect-Edge-23.0-rc1.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:51)
[18:52:11 WARN]:        at CoreProtect-Edge-23.0-rc1.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[18:52:11 WARN]:        at CoreProtect-Edge-23.0-rc1.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[18:52:11 WARN]:        at CoreProtect-Edge-23.0-rc1.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[18:52:11 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Skullians** [comment]
https://github.com/PlayPro/CoreProtect/issues/600#issuecomment-2265229174

**Comment by W07M0** [comment]
This happen after villager is killed

**Comment by Skullians** [comment]
Read my comment.

**Comment by Skullians** [comment]
‘things relates to villagers…’

**Comment by Steven-OS** [comment]
Hopefully this is fixed for 1.21 soon... the spam is real.

**Comment by Skullians** [comment]
Did you uh
Read my comment???

**Comment by tticehurst** [comment]
The fact it's taking this long for a 1.21 update is insane

**Comment by Steven-OS** [comment]
> Did you uh Read my comment???

I did, but no average person will know how to compile a jar. Even though yes I can, that won't fix the issue for the average person, hence why this needs to be updated for everyone.

**Comment by Skullians** [comment]
> > Did you uh Read my comment???
> 
> I did, but no average person will know how to compile a jar. Even though yes I can, that won't fix the issue for the average person, hence why this needs to be updated for everyone.

in my comment: ‘join the discord and I have a guide there that you can follow’

**Comment by Skullians** [comment]
A v23 jarfile will be released publicly free in a couple weeks iirc
