### ISSUE TITLE
Coreprotect spamms console in 1.21

### ISSUE THREAD

**Issue by JustSimplyGaming** [PlayPro/CoreProtect#610]
Hi i use Version "CoreProtect-Edge-23.0-RC3.jar" from Patreon and get the following spam in the console. Around 100 times in some minutes.

[18:00:44] [Thread-20/WARN]: java.io.NotSerializableException: org.bukkit.craftbukkit.entity.CraftVillager$CraftProfession
[18:00:44] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1200)
[18:00:44] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[18:00:44] [Thread-20/WARN]: 	at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[18:00:44] [Thread-20/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:00:44] [Thread-20/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[18:00:44] [Thread-20/WARN]: 	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[18:00:44] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[18:00:44] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[18:00:44] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[18:00:44] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[18:00:44] [Thread-20/WARN]: 	at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[18:00:44] [Thread-20/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:00:44] [Thread-20/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[18:00:44] [Thread-20/WARN]: 	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[18:00:44] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[18:00:44] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[18:00:44] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[18:00:44] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[18:00:44] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:28)
[18:00:44] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:50)
[18:00:44] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[18:00:44] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[18:00:44] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[18:00:44] [Thread-20/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[18:00:44] [Thread-20/WARN]: java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.next()" because "resultSet" is null
[18:00:44] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:52)
[18:00:44] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[18:00:44] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[18:00:44] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[18:00:44] [Thread-20/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[18:00:47] [Thread-20/WARN]: java.io.NotSerializableException: org.bukkit.craftbukkit.entity.CraftVillager$CraftProfession
[18:00:47] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1200)
[18:00:47] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[18:00:47] [Thread-20/WARN]: 	at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[18:00:47] [Thread-20/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:00:47] [Thread-20/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[18:00:47] [Thread-20/WARN]: 	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[18:00:47] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[18:00:47] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[18:00:47] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[18:00:47] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[18:00:47] [Thread-20/WARN]: 	at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[18:00:47] [Thread-20/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:00:47] [Thread-20/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[18:00:47] [Thread-20/WARN]: 	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[18:00:47] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[18:00:47] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[18:00:47] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[18:00:47] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[18:00:47] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:28)
[18:00:47] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:50)
[18:00:47] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[18:00:47] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[18:00:47] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[18:00:47] [Thread-20/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[18:00:47] [Thread-20/WARN]: java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.next()" because "resultSet" is null
[18:00:47] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:52)
[18:00:47] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[18:00:47] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[18:00:47] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[18:00:47] [Thread-20/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[18:00:48] [Thread-20/WARN]: java.io.NotSerializableException: org.bukkit.craftbukkit.entity.CraftVillager$CraftProfession
[18:00:48] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1200)
[18:00:48] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[18:00:48] [Thread-20/WARN]: 	at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[18:00:48] [Thread-20/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:00:48] [Thread-20/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[18:00:48] [Thread-20/WARN]: 	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[18:00:48] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[18:00:48] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[18:00:48] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[18:00:48] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[18:00:48] [Thread-20/WARN]: 	at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[18:00:48] [Thread-20/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:00:48] [Thread-20/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[18:00:48] [Thread-20/WARN]: 	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[18:00:48] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[18:00:48] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[18:00:48] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[18:00:48] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[18:00:48] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:28)
[18:00:48] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:50)
[18:00:48] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[18:00:48] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[18:00:48] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[18:00:48] [Thread-20/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[18:00:48] [Thread-20/WARN]: java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.next()" because "resultSet" is null
[18:00:48] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:52)
[18:00:48] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[18:00:48] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[18:00:48] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[18:00:48] [Thread-20/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[18:00:49] [Thread-20/WARN]: java.io.NotSerializableException: org.bukkit.craftbukkit.entity.CraftVillager$CraftProfession
[18:00:49] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1200)
[18:00:49] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[18:00:49] [Thread-20/WARN]: 	at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[18:00:49] [Thread-20/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:00:49] [Thread-20/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[18:00:49] [Thread-20/WARN]: 	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[18:00:49] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[18:00:49] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[18:00:49] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[18:00:49] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[18:00:49] [Thread-20/WARN]: 	at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[18:00:49] [Thread-20/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:00:49] [Thread-20/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[18:00:49] [Thread-20/WARN]: 	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[18:00:49] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[18:00:49] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[18:00:49] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[18:00:49] [Thread-20/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[18:00:49] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:28)
[18:00:49] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:50)
[18:00:49] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[18:00:49] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[18:00:49] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[18:00:49] [Thread-20/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[18:00:49] [Thread-20/WARN]: java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.next()" because "resultSet" is null
[18:00:49] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:52)
[18:00:49] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[18:00:49] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[18:00:49] [Thread-20/WARN]: 	at CoreProtect-Edge-23.0-RC3.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[18:00:49] [Thread-20/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Skullians** [comment]
You are using CoreProtect v23-RC3.
Update to v23.

**Comment by Skullians** [comment]
The issue you are experiencing was resolved in v23.

**Comment by n-aspen** [comment]
https://github.com/PlayPro/CoreProtect/issues/589

**Comment by JustSimplyGaming** [comment]
Ah okay, didnt saw it on Patreon, found it now by searching active.

**Comment by DereC4** [comment]
Happens to me too, glad we put out an update!
