### ISSUE TITLE
error spam

### ISSUE THREAD

**Issue by Dg32z** [PlayPro/CoreProtect#619]
[20:13:54 WARN]: java.io.NotSerializableException: org.bukkit.craftbukkit.entity.CraftVillager$CraftProfession
[20:13:54 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1200)
[20:13:54 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[20:13:54 WARN]:        at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[20:13:54 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[20:13:54 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[20:13:54 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[20:13:54 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[20:13:54 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[20:13:54 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[20:13:54 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[20:13:54 WARN]:        at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[20:13:54 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[20:13:54 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[20:13:54 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[20:13:54 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[20:13:54 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[20:13:54 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[20:13:54 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[20:13:54 WARN]:        at [C]CoreProtect-Edge.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:28)
[20:13:54 WARN]:        at [C]CoreProtect-Edge.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:49)
[20:13:54 WARN]:        at [C]CoreProtect-Edge.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[20:13:54 WARN]:        at [C]CoreProtect-Edge.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[20:13:54 WARN]:        at [C]CoreProtect-Edge.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[20:13:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

Version: CoreProtect version 23.0-rc1

> ver
[20:18:12 INFO]: Checking version, please wait...
[20:18:13 INFO]: This server is running Luminol version 1.21.1-DEV-dev/1.21.1@7c312e7 (2024-08-17T05:31:51Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are 4 version(s) behind
Download the new version at: https://github.com/LuminolMC/Luminol
Previous version: 1.20.6-DEV-e8a4308 (MC: 1.20.6)

**Comment by Skullians** [comment]
You are 4 versions out of date. Update and your issue will be resolved.
