### ISSUE TITLE
Composter is not a container

### ISSUE THREAD

**Issue by Almtesh** [PlayPro/CoreProtect#621]
Hello,

I noticed that CoreProtect 22.4 on CraftBukkit 1.21 server send an error in the logs:
```
[18:06:41] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to CoreProtect v22.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[bukkit-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[bukkit-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:600) ~[bukkit-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:587) ~[bukkit-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.block.entity.TileEntityHopper.a(TileEntityHopper.java:230) ~[craftbukkit-1.21-R0.1-SNAPSHOT.jar:4226-Bukkit-2889b3a]
        at net.minecraft.world.level.block.entity.TileEntityHopper.a(TileEntityHopper.java:166) ~[craftbukkit-1.21-R0.1-SNAPSHOT.jar:4226-Bukkit-2889b3a]
        at net.minecraft.world.level.block.entity.TileEntityHopper.a(TileEntityHopper.java:151) ~[craftbukkit-1.21-R0.1-SNAPSHOT.jar:4226-Bukkit-2889b3a]
        at net.minecraft.world.level.chunk.Chunk$a.a(Chunk.java:898) ~[craftbukkit-1.21-R0.1-SNAPSHOT.jar:4226-Bukkit-2889b3a]
        at net.minecraft.world.level.chunk.Chunk$d.a(Chunk.java:851) ~[craftbukkit-1.21-R0.1-SNAPSHOT.jar:4226-Bukkit-2889b3a]
        at net.minecraft.world.level.World.T(World.java:641) ~[craftbukkit-1.21-R0.1-SNAPSHOT.jar:4226-Bukkit-2889b3a]
        at net.minecraft.server.level.WorldServer.a(WorldServer.java:458) ~[craftbukkit-1.21-R0.1-SNAPSHOT.jar:4226-Bukkit-2889b3a]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1421) ~[craftbukkit-1.21-R0.1-SNAPSHOT.jar:4226-Bukkit-2889b3a]
        at net.minecraft.server.dedicated.DedicatedServer.c(DedicatedServer.java:393) ~[craftbukkit-1.21-R0.1-SNAPSHOT.jar:4226-Bukkit-2889b3a]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1284) ~[craftbukkit-1.21-R0.1-SNAPSHOT.jar:4226-Bukkit-2889b3a]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1036) ~[craftbukkit-1.21-R0.1-SNAPSHOT.jar:4226-Bukkit-2889b3a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[craftbukkit-1.21-R0.1-SNAPSHOT.jar:4226-Bukkit-2889b3a]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException
```
To cause that exception, I build a simple contraption with, from up to down, a chest, a hopper, a composter, a hopper and a chest. When I put compostable items in the upper chest, this error message is sent in the logs everytime a item goes from the upper hopper to the composter.

If you need more info, please ask me.

Regards,
Almtesh

**Comment by Skullians** [comment]
Fixed in v23.
22.4 does not support 1.21

**Comment by Almtesh** [comment]
OK, thanks for your swift answer. Where can I find the v23, I only see v22.4.

**Comment by Skullians** [comment]
v23 is currently only available to Patrons or you can compile it yourself for free

**Comment by Almtesh** [comment]
Thanks, i close the issue.
