### ISSUE TITLE
an error was happened when im trying use coreprotect

### ISSUE THREAD

**Issue by 837cyo84o2rcj** [PlayPro/CoreProtect#631]
I installed CoreProtect for my server to prevent it from being destroyed. But when I use the command "/co rollback <a player's name here> time:5m" (meaning restore everything the player has destroyed in the last 5 minutes) for 4 times, the destroyed thing is restored successfully, but the server's control table gives these error messages:

[00:49:34] [User Authenticator #0/INFO]: UUID of player CHNdhjhf67 is 9f7b3446-8716-458e-9842-8b1bae142b03
[00:49:38] [Server thread/INFO]: CHNdhjhf67 joined the game
[00:49:38] [Server thread/INFO]: CHNdhjhf67[/110.153.246.21:4498] logged in with entity id 101 at ([world]-369.76592707881736, -13.35, -1049.5)
[00:49:47] [Craft Scheduler Thread - 1092 - AuthMe/INFO]: [AuthMe] CHNdhjhf67 logged in 110.153.246.21
[00:53:36] [Server thread/INFO]: CHNdhjhf67 has made the advancement [Lighten Up]
[00:55:01] [Async Chat Thread - #2/INFO]: <CHNdhjhf67> w
[01:06:48] [Server thread/INFO]: Grim » CHNdhjhf67 触发了 RotationPlace (x10) pre-flying
[01:09:52] [Thread-6/WARN]: java.io.NotSerializableException: org.bukkit.craftbukkit.entity.CraftVillager$CraftProfession
[01:09:52] [Thread-6/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1200)
[01:09:52] [Thread-6/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[01:09:52] [Thread-6/WARN]: 	at java.base/java.util.ArrayList.writeObject(ArrayList.java:949)
[01:09:52] [Thread-6/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[01:09:52] [Thread-6/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[01:09:52] [Thread-6/WARN]: 	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1078)
[01:09:52] [Thread-6/WARN]: 	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[01:09:52] [Thread-6/WARN]: 	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[01:09:52] [Thread-6/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[01:09:52] [Thread-6/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[01:09:52] [Thread-6/WARN]: 	at java.base/java.util.ArrayList.writeObject(ArrayList.java:949)
[01:09:52] [Thread-6/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[01:09:52] [Thread-6/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[01:09:52] [Thread-6/WARN]: 	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1078)
[01:09:52] [Thread-6/WARN]: 	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[01:09:52] [Thread-6/WARN]: 	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[01:09:52] [Thread-6/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[01:09:52] [Thread-6/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[01:09:52] [Thread-6/WARN]: 	at CoreProtect-22.4.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:27)
[01:09:52] [Thread-6/WARN]: 	at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:49)
[01:09:52] [Thread-6/WARN]: 	at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[01:09:52] [Thread-6/WARN]: 	at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[01:09:52] [Thread-6/WARN]: 	at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[01:09:52] [Thread-6/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
[01:09:52] [Thread-6/WARN]: java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.next()" because "resultSet" is null
[01:09:52] [Thread-6/WARN]: 	at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:51)
[01:09:52] [Thread-6/WARN]: 	at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[01:09:52] [Thread-6/WARN]: 	at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[01:09:52] [Thread-6/WARN]: 	at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[01:09:52] [Thread-6/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1570)

the server version is paper-1.21.1-52, and i installed jdk 22 to run it.

**Comment by Skullians** [comment]
Hey, v22.4 doesn’t support 1.21.
v23 solves this issue and is only currently available to patrons or you can compile it yourself for free

**Comment by 837cyo84o2rcj** [comment]
So when will the v23 version be available to the public for free download, or how should I compile v23 myself?

**Comment by Skullians** [comment]
As far as we’ve been told, a couple weeks.
I have a guide for compiling on the Discord if you want it

**Comment by 837cyo84o2rcj** [comment]
i think i can try to compiling it, so can you give me the guide? : )

**Comment by Skullians** [comment]
Join the discord and ask for it
