### ISSUE TITLE
Error 1.21

### ISSUE THREAD

**Issue by MazzSavoy** [PlayPro/CoreProtect#639]
[00:41:26 INFO]: Unknown or incomplete command, see below for error
[00:40:54 WARN]: java.io.NotSerializableException: org.bukkit.craftbukkit.entity.CraftCat$CraftType
[00:40:54 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1200)
[00:40:54 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[00:40:54 WARN]:        at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[00:40:54 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[00:40:54 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[00:40:54 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[00:40:54 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[00:40:54 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[00:40:54 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[00:40:54 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[00:40:54 WARN]:        at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[00:40:54 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[00:40:54 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[00:40:54 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[00:40:54 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[00:40:54 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[00:40:54 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[00:40:54 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[00:40:54 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:27)
[00:40:54 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:49)
[00:40:54 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[00:40:54 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[00:40:54 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[00:40:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[00:40:54 WARN]: java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.next()" because "resultSet" is null
[00:40:54 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:51)
[00:40:54 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[00:40:54 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[00:40:54 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)

**Comment by Skullians** [comment]
v22.4 does not support 1.21

**Comment by Skullians** [comment]
This issue is fixed in v23. It is currently only available to patrons of you can compile it yourself for free.

**Comment by tticehurst** [comment]
Don't worry, it'll be available "in a few weeks" - This was about a month ago mind you so :shrug:

**Comment by Klover91** [comment]
> This issue is fixed in v23. It is currently only available to patrons or you can compile it yourself for free.

where is the link for your patreon? i really need support for 1.21

**Comment by Skullians** [comment]
> > This issue is fixed in v23. It is currently only available to patrons or you can compile it yourself for free.
> 
> where is the link for your patreon? i really need support for 1.21

https://coreprotect.net/patreon/
