### ISSUE TITLE
Could not pass event EntityDeathEvent to CoreProtect v23.1

### ISSUE THREAD

**Issue by Romainof** [PlayPro/CoreProtect#644]
Hey,

I recently updated CoreProtect to version 23.1, a new error has appeared :

```
[11:02:54] [Server thread/ERROR]: Could not pass event EntityDeathEvent to CoreProtect v23.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_21_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:914) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1761) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1708) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1528) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.world.entity.monster.EntityZombie.a(EntityZombie.java:306) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.world.entity.player.EntityHuman.e(EntityHuman.java:1296) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.server.level.EntityPlayer.e(EntityPlayer.java:2165) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.server.network.PlayerConnection$3.a(PlayerConnection.java:2473) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(SourceFile:174) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:74) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2385) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:61) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:15) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:35) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:162) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1270) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:203) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:136) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1249) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1242) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:145) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1207) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.server.MinecraftServer.v_(MinecraftServer.java:1214) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1078) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4272-Spigot-34bd42b-76f59e3]
	at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.lang.NoSuchMethodError: 'java.lang.String org.bukkit.NamespacedKey.asString()'
	at net.coreprotect.bukkit.Bukkit_v1_21.getRegistryKey(Bukkit_v1_21.java:48) ~[?:?]
	at net.coreprotect.listener.entity.EntityDeathListener.logEntityDeath(EntityDeathListener.java:436) ~[?:?]
	at net.coreprotect.listener.entity.EntityDeathListener.onEntityDeath(EntityDeathListener.java:554) ~[?:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	... 31 more
```

Server version : 1.21

Thanks in advance for your help!

**Comment by Intelli** [comment]
Should already be fixed here: https://github.com/PlayPro/CoreProtect/commit/ad4b0ddf24addbe860ea0c593aab7da2a152cc9c
