### ISSUE TITLE
Paper 1.21.1-119 -- Error/Bug

### ISSUE THREAD

**Issue by tomasalias** [PlayPro/CoreProtect#656]
[09:03:34] [Server thread/INFO]: Villager Villager['Farmer'/13438, uuid='5c748df5-43c7-410a-8e67-7dffea501c75', l='ServerLevel[world]', x=1105.75, y=76.00, z=1485.70, cpos=[69, 92], tl=150365, v=true] died, message: 'Farmer was slain by Zombie'
[09:03:35] [Thread-31/WARN]: java.io.NotSerializableException: org.bukkit.craftbukkit.entity.CraftVillager$CraftProfession
[09:03:35] [Thread-31/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1200)
[09:03:35] [Thread-31/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[09:03:35] [Thread-31/WARN]: 	at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[09:03:35] [Thread-31/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[09:03:35] [Thread-31/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[09:03:35] [Thread-31/WARN]: 	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[09:03:35] [Thread-31/WARN]: 	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[09:03:35] [Thread-31/WARN]: 	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[09:03:35] [Thread-31/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[09:03:35] [Thread-31/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[09:03:35] [Thread-31/WARN]: 	at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[09:03:35] [Thread-31/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[09:03:35] [Thread-31/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[09:03:35] [Thread-31/WARN]: 	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[09:03:35] [Thread-31/WARN]: 	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[09:03:35] [Thread-31/WARN]: 	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[09:03:35] [Thread-31/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[09:03:35] [Thread-31/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[09:03:35] [Thread-31/WARN]: 	at CoreProtect-22.4.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:27)
[09:03:35] [Thread-31/WARN]: 	at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:49)
[09:03:35] [Thread-31/WARN]: 	at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[09:03:35] [Thread-31/WARN]: 	at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[09:03:35] [Thread-31/WARN]: 	at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[09:03:35] [Thread-31/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[09:03:35] [Thread-31/WARN]: java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.next()" because "resultSet" is null
[09:03:35] [Thread-31/WARN]: 	at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:51)
[09:03:35] [Thread-31/WARN]: 	at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[09:03:35] [Thread-31/WARN]: 	at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[09:03:35] [Thread-31/WARN]: 	at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[09:03:35] [Thread-31/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by vacla** [comment]
Fixed in v23, free available on Patreon rn

**Comment by tomasalias** [comment]
Oh, thanks.
