### ISSUE TITLE
"Villager was squished too much" warning

### ISSUE THREAD

**Issue by AndreiWasFound** [PlayPro/CoreProtect#657]
Using CoreProtect v22.4 I get this warning message every time one of my villagers dies in my villager farm. There is not any problem with it, i don't think it affects me in any way but indeed this looks like a bug.

`[16:46:28 INFO]: Villager Villager['Villager'/1896, uuid='b701639d-3727-4024-b0a9-f4af004090e9', l='ServerLevel[world]', x=-302.30, y=61.00, z=12.84, cpos=[-19, 0], tl=132974, v=true] died, message: 'Villager was squished too much'
[16:46:29 WARN]: java.io.NotSerializableException: org.bukkit.craftbukkit.entity.CraftVillager$CraftProfession
[16:46:29 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
[16:46:29 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source)
[16:46:29 WARN]:        at java.base/java.util.ArrayList.writeObject(Unknown Source)
[16:46:29 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[16:46:29 WARN]:        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[16:46:29 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
[16:46:29 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source)
[16:46:29 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
[16:46:29 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
[16:46:29 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source)
[16:46:29 WARN]:        at java.base/java.util.ArrayList.writeObject(Unknown Source)
[16:46:29 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[16:46:29 WARN]:        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[16:46:29 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
[16:46:29 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source)
[16:46:29 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
[16:46:29 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
[16:46:29 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source)
[16:46:29 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:27)
[16:46:29 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:49)
[16:46:29 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[16:46:29 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[16:46:29 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[16:46:29 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[16:46:29 WARN]: java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.next()" because "resultSet" is null
[16:46:29 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:51)
[16:46:29 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[16:46:29 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[16:46:29 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[16:46:29 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by vacla** [comment]
Fixed in V23.0 , download see: https://www.patreon.com/posts/113032756
