### ISSUE TITLE
Could not pass event InventoryMoveItemEvent to CoreProtect v22.4

### ISSUE THREAD

**Issue by mspet23** [PlayPro/CoreProtect#664]
````diff
- [Fri 03:01:59 ERROR Minecraft] Could not pass event InventoryMoveItemEvent to CoreProtect v22.4
java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getBlockX()" because "destinationLocation" is null
	at CoreProtect-22.4 (1).jar//net.coreprotect.listener.player.HopperPushListener.processHopperPush(HopperPushListener.java:23)
	at CoreProtect-22.4 (1).jar//net.coreprotect.listener.player.InventoryChangeListener.onInventoryMoveItemEvent(InventoryChangeListener.java:345)
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
	at org.bukkit.event.Event.callEvent(Event.java:45)
	at net.minecraft.world.level.block.entity.HopperBlockEntity.callPushMoveEvent(HopperBlockEntity.java:318)
	at net.minecraft.world.level.block.entity.HopperBlockEntity.hopperPush(HopperBlockEntity.java:244)
	at net.minecraft.world.level.block.entity.HopperBlockEntity.ejectItems(HopperBlockEntity.java:429)
	at net.minecraft.world.level.block.entity.HopperBlockEntity.tryMoveItems(HopperBlockEntity.java:188)
	at net.minecraft.world.level.block.entity.HopperBlockEntity.pushItemsTick(HopperBlockEntity.java:169)
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1325)
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1277)
	at net.minecraft.world.level.Level.tickBlockEntities(Level.java:1056)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:775)
	at net.minecraft.server.MinecraftServe```  `

**Comment by mspet23** [comment]
1.19.4 purpur

**Comment by Skullians** [comment]
Fixed in v23, available on patreon free tier
