### ISSUE TITLE
Spam console CoreProtect v23.0

### ISSUE THREAD

**Issue by Nektoo** [PlayPro/CoreProtect#669]
[07:55:36 WARN]: java.io.NotSerializableException: org.bukkit.craftbukkit.attribute.CraftAttribute
[07:55:36 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1200)
[07:55:36 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[07:55:36 WARN]:        at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[07:55:36 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[07:55:36 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[07:55:36 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[07:55:36 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[07:55:36 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[07:55:36 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[07:55:36 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[07:55:36 WARN]:        at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[07:55:36 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[07:55:36 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[07:55:36 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[07:55:36 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[07:55:36 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[07:55:36 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[07:55:36 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[07:55:36 WARN]:        at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[07:55:36 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[07:55:36 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[07:55:36 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[07:55:36 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[07:55:36 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[07:55:36 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[07:55:36 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[07:55:36 WARN]:        at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:28)
[07:55:36 WARN]:        at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:50)
[07:55:36 WARN]:        at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[07:55:36 WARN]:        at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:206)
[07:55:36 WARN]:        at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[07:55:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[07:55:36 WARN]: java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.next()" because "resultSet" is null
[07:55:36 WARN]:        at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:52)
[07:55:36 WARN]:        at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[07:55:36 WARN]:        at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:206)
[07:55:36 WARN]:        at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[07:55:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[07:55:59 WARN]: java.io.NotSerializableException: org.bukkit.craftbukkit.attribute.CraftAttribute
[07:55:59 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1200)
[07:55:59 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[07:55:59 WARN]:        at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[07:55:59 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[07:55:59 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[07:55:59 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[07:55:59 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[07:55:59 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[07:55:59 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[07:55:59 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[07:55:59 WARN]:        at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[07:55:59 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[07:55:59 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[07:55:59 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[07:55:59 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[07:55:59 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[07:55:59 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[07:55:59 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[07:55:59 WARN]:        at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[07:55:59 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[07:55:59 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[07:55:59 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[07:55:59 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[07:55:59 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[07:55:59 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[07:55:59 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[07:55:59 WARN]:        at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:28)
[07:55:59 WARN]:        at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:50)
[07:55:59 WARN]:        at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[07:55:59 WARN]:        at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:206)
[07:55:59 WARN]:        at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[07:55:59 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[07:55:59 WARN]: java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.next()" because "resultSet" is null
[07:55:59 WARN]:        at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:52)
[07:55:59 WARN]:        at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[07:55:59 WARN]:        at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:206)
[07:55:59 WARN]:        at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[07:55:59 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by XeonG** [comment]
yeah same

**Comment by TheFruxz** [comment]
also a massive problem here

**Comment by Intelli** [comment]
This issue can be resolved by either running MC 1.21.1, or using the latest build of CoreProtect.

Fixed here: https://github.com/PlayPro/CoreProtect/commit/b3db65d07d129e77f13b433e4d29729d4a971651

Latest Patreon development build: https://www.patreon.com/posts/coreprotect-edge-117654146
