### ISSUE TITLE
coreprotect does not record the killing of villagers 

### ISSUE THREAD

**Issue by HMY369** [PlayPro/CoreProtect#671]
https://github.com/user-attachments/assets/5e2b004f-0668-4779-964c-5c9b8e48cdf2

logs:
[18:43:06 INFO]: Villager Villager['Villager'/8116884, uuid='uuid', l='ServerLevel[world]', x=20084.72, y=72.00, z=51529.41, cpos=[1255, 3220], tl=54, v=true] died, message: 'Villager was slain by ME'
[18:43:06 WARN]: java.io.NotSerializableException: org.bukkit.craftbukkit.entity.CraftVillager$CraftProfession
[18:43:06 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1200)
[18:43:06 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[18:43:06 WARN]:        at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[18:43:06 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:43:06 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[18:43:06 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[18:43:06 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[18:43:06 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[18:43:06 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[18:43:06 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[18:43:06 WARN]:        at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[18:43:06 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:43:06 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[18:43:06 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[18:43:06 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[18:43:06 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[18:43:06 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[18:43:06 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[18:43:06 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:27)
[18:43:06 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:49)
[18:43:06 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[18:43:06 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[18:43:06 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[18:43:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[18:43:06 WARN]: java.lang.NullPointerException

**Comment by vacla** [comment]
Fixed in v23, you can find it under patreon community edition (free)

**Comment by Dragsio** [comment]
https://github.com/PlayPro/CoreProtect/issues/688#issuecomment-2548417653
