### ISSUE TITLE
Could not pass event InventoryMoveItemEvent to CoreProtect

### ISSUE THREAD

**Issue by abc13131412** [PlayPro/CoreProtect#673]
I got this error message when I starting up my server.
Version: Arclight 1.20.4
```
[0811月2024 17:52:15.555] [Server thread/ERROR] [Minecraft/]: Could not pass event InventoryMoveItemEvent to CoreProtect v22.4
Server threadEx org.bukkit.event.EventException: null
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight-1.20.4-1.0.4-80ec5df.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:600) ~[arclight-1.20.4-1.0.4-80ec5df.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:587) ~[arclight-1.20.4-1.0.4-80ec5df.jar:?]
	at net.minecraft.class_2614.eject$bid000$arclight$moveItem(HopperBlockEntityMixin.java:585) ~[server-intermediary.jar:?]
	at net.minecraft.class_2614.method_11246(HopperBlockEntityMixin.java:158) ~[server-intermediary.jar:?]
	at net.minecraft.class_2614.method_11243(HopperBlockEntityMixin.java:115) ~[server-intermediary.jar:?]
	at net.minecraft.class_2614.redirect$bid000$arclight$hopperCheck(HopperBlockEntityMixin.java:561) ~[server-intermediary.jar:?]
	at net.minecraft.class_2614.method_31692(HopperBlockEntityMixin.java:102) ~[server-intermediary.jar:?]
	at net.minecraft.class_2818$class_5563.method_31703(LevelChunk_BoundTickingBlockEntityMixin.java:662) ~[server-intermediary.jar:?]
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_18471(LevelMixin.java:482) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(ServerLevelMixin.java:404) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServerMixin.java:948) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(DedicatedServerMixin_Vanilla.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServerMixin.java:845) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServerMixin.java:2127) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServerMixin.java:270) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getBlockX()" because "destinationLocation" is null
	at net.coreprotect.listener.player.HopperPushListener.processHopperPush(HopperPushListener.java:23) ~[?:?]
	at net.coreprotect.listener.player.InventoryChangeListener.onInventoryMoveItemEvent(InventoryChangeListener.java:345) ~[?:?]
	... 18 more
```

**Comment by Skullians** [comment]
This was fixed in v23 afaik

**Comment by abc13131412** [comment]
Ah OK
