### ISSUE TITLE
Skin error for 1.21

### ISSUE THREAD

**Issue by JHarris12345** [PlayPro/CoreProtect#675]
On 1.21 I am getitng spammed with this error

`
[11:21:15 WARN]: java.sql.SQLSyntaxErrorException: Unknown column 'skin' in 'field list'
[11:21:15 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:112)
[11:21:15 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:113)
[11:21:15 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:938)
[11:21:15 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1106)
[11:21:15 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1045)
[11:21:15 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1369)
[11:21:15 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1030)
[11:21:15 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[11:21:15 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[11:21:15 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.statement.SkullStatement.insert(SkullStatement.java:28)
[11:21:15 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.logger.SkullPlaceLogger.log(SkullPlaceLogger.java:38)
[11:21:15 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:20)
[11:21:15 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:148)
[11:21:15 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:21:15 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[11:21:15 WARN]: java.sql.SQLException: Illegal operation on empty result set.
[11:21:15 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
[11:21:15 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[11:21:15 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:81)
[11:21:15 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:55)
[11:21:15 WARN]:        at com.mysql.cj.jdbc.result.ResultSetImpl.checkRowPos(ResultSetImpl.java:519)
[11:21:15 WARN]:        at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1252)
[11:21:15 WARN]:        at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:818)
[11:21:15 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.hikari.pool.HikariProxyResultSet.getInt(HikariProxyResultSet.java)
[11:21:15 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.logger.SkullPlaceLogger.log(SkullPlaceLogger.java:47)
[11:21:15 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:20)
[11:21:15 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:148)
[11:21:15 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[11:21:15 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)`

**Comment by ShortByte** [comment]
Hey @JHarris12345, I also got these errors. To fix it yourself, you just need to add the column to the database.

For example with these commands:
`ALTER TABLE coreprotect.co_skull ADD skin varchar(255) DEFAULT NULL NULL;`

**Comment by brozi1620** [comment]
Good. Do I need to open the FILE to make "ALTER TABLE coreprotect.co_skull, ADD a skin varchar(255) BY DEFAULT NULL NULL;"?

**Comment by ShortByte** [comment]
If you have it running with a SQLite, yes. You have to open the file with a database editor. But you should do this when the server is offline. If you have a MariaDB or MySQL server connected, you can do it live with a DB tool or DB console.

**Comment by JHarris12345** [comment]
I'd rather @Intelli adds an official fix for it though

**Comment by Skullians** [comment]
This was either:
You running an unsupported mc version (1.21.x not supported on 22.4), or you compiled the plugin yourself improperly.

**Comment by JHarris12345** [comment]
> This was either: You running an unsupported mc version (1.21.x not supported on 22.4), or you compiled the plugin yourself improperly.

Where is the download for 1.21.X. I cloned the latest repo and built it. So I think it's an issue with the source

**Comment by Skullians** [comment]
You must first run https://www.patreon.com/posts/113032756 to patch your database, and then compile coreprotect with a version of 23.0 and branch ‘development’ in the pom.xml.

**Comment by Skullians** [comment]
We have guides on the Coreprotect discord if you need it.
