### ISSUE TITLE
I keep getting NullPointerException's and NotSerializableException's

### ISSUE THREAD

**Issue by v1peeer** [PlayPro/CoreProtect#683]
Every 5 seconds, not sure at what conditions, but when players are online, I get my console spammed with these errors, if I have the entity kill logs enabled.
I'm running paper 1.21.3 with ~10 players playing survival at the same time and a few plugins like headdrop, geyser.
```[20:00:50 WARN]: java.io.NotSerializableException: org.bukkit.craftbukkit.attribute.CraftAttribute
[20:00:50 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
[20:00:50 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source)
[20:00:50 WARN]:        at java.base/java.util.ArrayList.writeObject(Unknown Source)
[20:00:50 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[20:00:50 WARN]:        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[20:00:50 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
[20:00:50 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source)
[20:00:50 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
[20:00:50 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
[20:00:50 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source)
[20:00:50 WARN]:        at java.base/java.util.ArrayList.writeObject(Unknown Source)
[20:00:50 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[20:00:50 WARN]:        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[20:00:50 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
[20:00:50 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source)
[20:00:50 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
[20:00:50 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
[20:00:50 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source)
[20:00:50 WARN]:        at java.base/java.util.ArrayList.writeObject(Unknown Source)
[20:00:50 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[20:00:50 WARN]:        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[20:00:50 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
[20:00:50 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source)
[20:00:50 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
[20:00:50 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
[20:00:50 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source)
[20:00:50 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:27)
[20:00:50 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:49)
[20:00:50 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[20:00:50 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[20:00:50 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[20:00:50 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[20:00:50 WARN]: java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.next()" because "resultSet" is null
[20:00:50 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:51)
[20:00:50 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[20:00:50 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[20:00:50 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[20:00:50 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[20:00:55 WARN]: java.io.NotSerializableException: org.bukkit.craftbukkit.attribute.CraftAttribute
[20:00:55 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
[20:00:55 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source)
[20:00:55 WARN]:        at java.base/java.util.ArrayList.writeObject(Unknown Source)
[20:00:55 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[20:00:55 WARN]:        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[20:00:55 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
[20:00:55 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source)
[20:00:55 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
[20:00:55 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
[20:00:55 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source)
[20:00:55 WARN]:        at java.base/java.util.ArrayList.writeObject(Unknown Source)
[20:00:55 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[20:00:55 WARN]:        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[20:00:55 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
[20:00:55 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source)
[20:00:55 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
[20:00:55 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
[20:00:55 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source)
[20:00:55 WARN]:        at java.base/java.util.ArrayList.writeObject(Unknown Source)
[20:00:55 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[20:00:55 WARN]:        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[20:00:55 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
[20:00:55 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source)
[20:00:55 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
[20:00:55 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
[20:00:55 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source)
[20:00:55 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:27)
[20:00:55 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:49)
[20:00:55 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[20:00:55 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[20:00:55 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[20:00:55 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[20:00:55 WARN]: java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.next()" because "resultSet" is null
[20:00:55 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:51)
[20:00:55 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[20:00:55 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[20:00:55 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[20:00:55 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[20:01:14 WARN]: java.io.NotSerializableException: org.bukkit.craftbukkit.attribute.CraftAttribute
[20:01:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
[20:01:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source)
[20:01:14 WARN]:        at java.base/java.util.ArrayList.writeObject(Unknown Source)
[20:01:14 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[20:01:14 WARN]:        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[20:01:14 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
[20:01:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source)
[20:01:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
[20:01:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
[20:01:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source)
[20:01:14 WARN]:        at java.base/java.util.ArrayList.writeObject(Unknown Source)
[20:01:14 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[20:01:14 WARN]:        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[20:01:14 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
[20:01:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source)
[20:01:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
[20:01:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
[20:01:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source)
[20:01:14 WARN]:        at java.base/java.util.ArrayList.writeObject(Unknown Source)
[20:01:14 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[20:01:14 WARN]:        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[20:01:14 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
[20:01:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source)
[20:01:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
[20:01:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
[20:01:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source)
[20:01:14 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:27)
[20:01:14 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:49)
[20:01:14 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[20:01:14 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[20:01:14 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[20:01:14 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[20:01:14 WARN]: java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.next()" because "resultSet" is null
[20:01:14 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:51)
[20:01:14 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[20:01:14 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[20:01:14 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[20:01:14 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)```

**Comment by vacla** [comment]
@v1peeer fixed in the latest github code already.

**Comment by v1peeer** [comment]
Ah okay, thanks!

**Comment by ThatProgrammerr** [comment]
Is this a problem in an older version, or is this already built somewhere to download that isn't github?

**Comment by Intelli** [comment]
Latest builds are posted at http://coreprotect.net
