### ISSUE TITLE
java.io.NotSerializableException: org.bukkit.craftbukkit.v1_21_R3.attribute.CraftAttribute 

### ISSUE THREAD

**Issue by XeonG** [PlayPro/CoreProtect#684]
On 1.21.3/4  with latest release I have seen to download

`[00:41:17] [Thread-22/WARN]: java.io.NotSerializableException: org.bukkit.craftbukkit.v1_21_R3.attribute.CraftAttribute
>[00:41:17] [Thread-22/WARN]: at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1200)
[00:41:17] [Thread-22/WARN]: at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[00:41:17] [Thread-22/WARN]: at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[00:41:17] [Thread-22/WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[00:41:17] [Thread-22/WARN]: at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[00:41:17] [Thread-22/WARN]: at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[00:41:17] [Thread-22/WARN]: at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[00:41:17] [Thread-22/WARN]: at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[00:41:17] [Thread-22/WARN]: at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[00:41:17] [Thread-22/WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[00:41:17] [Thread-22/WARN]: at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[00:41:17] [Thread-22/WARN]: at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[00:41:17] [Thread-22/WARN]: at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[00:41:17] [Thread-22/WARN]: at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[00:41:17] [Thread-22/WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[00:41:17] [Thread-22/WARN]: at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[00:41:17] [Thread-22/WARN]: at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[00:41:17] [Thread-22/WARN]: at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[00:41:17] [Thread-22/WARN]: at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[00:41:17] [Thread-22/WARN]: at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[00:41:17] [Thread-22/WARN]: at net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:27)
[00:41:17] [Thread-22/WARN]: at net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:49)
[00:41:17] [Thread-22/WARN]: at net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[00:41:17] [Thread-22/WARN]: at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[00:41:17] [Thread-22/WARN]: at java.base/java.lang.Thread.run(Thread.java:1583)
[00:41:17] [Thread-22/WARN]: java.sql.SQLException: Illegal operation on empty result set.
[00:41:17] [Thread-22/WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
[00:41:17] [Thread-22/WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[00:41:17] [Thread-22/WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:81)
[00:41:17] [Thread-22/WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:55)
[00:41:17] [Thread-22/WARN]: at com.mysql.cj.jdbc.result.ResultSetImpl.checkRowPos(ResultSetImpl.java:541)
[00:41:17] [Thread-22/WARN]: at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1304)
[00:41:17] [Thread-22/WARN]: at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:852)
[00:41:17] [Thread-22/WARN]: at net.coreprotect.hikari.pool.HikariProxyResultSet.getInt(HikariProxyResultSet.java)
[00:41:17] [Thread-22/WARN]: at net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:58)
[00:41:17] [Thread-22/WARN]: at net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[00:41:17] [Thread-22/WARN]: at net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[00:41:17] [Thread-22/WARN]: at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[00:41:17] [Thread-22/WARN]: at java.base/java.lang.Thread.run(Thread.java:1583)`

**Comment by Jonathaan44** [comment]
I'm getting the same error, might be a bug in the version.

**Comment by Intelli** [comment]
Still unable to replicate. If someone knows how to replicate a CraftAttribute error, please let me know.

**Comment by LegalSmeagol** [comment]
Also getting this error frequently. I'm honestly not sure what triggers it though, sadly.

**Comment by XeonG** [comment]
I just compiled the github version with maven and that is 22.4 or something and error is gone... make sure to add in pom.xml 
    <project.branch>development</project.branch>  then just do 'mvn package'  obviously you have to setup those tools but yeah its do able.

and that build will work on latest spigot build at least for me with none of the errors ... glad they keep the source available hope they don't remove it as its the new log block for small servers is useful

**Comment by Intelli** [comment]
This specific issue was already resolved here: https://github.com/PlayPro/CoreProtect/commit/2780a9af278e0da9432600ba22c50ed9d4afdcf4
