### ISSUE TITLE
Kill logging error

### ISSUE THREAD

**Issue by forditt** [PlayPro/CoreProtect#688]
[Sun 22:18:11 INFO  Minecraft/Villager] Villager Villager['Villager'/23017, uuid='aa0a860e-3c09-4db4-ab1e-47b6499853be', l='ServerLevel[world]', x=-796.30, y=60.00, z=-460.70, cpos=[-50, -29], tl=132, v=true] died, message: 'Villager was slain by Zombie'
! [Sun 22:18:12 WARN ] java.io.NotSerializableException: org.bukkit.craftbukkit.entity.CraftVillager$CraftProfession
! [Sun 22:18:12 WARN ]     at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1200)
! [Sun 22:18:12 WARN ]     at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
! [Sun 22:18:12 WARN ]     at java.base/java.util.ArrayList.writeObject(ArrayList.java:949)
! [Sun 22:18:12 WARN ]     at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
! [Sun 22:18:12 WARN ]     at java.base/java.lang.reflect.Method.invoke(Method.java:580)
! [Sun 22:18:12 WARN ]     at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1078)
! [Sun 22:18:12 WARN ]     at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
! [Sun 22:18:12 WARN ]     at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
! [Sun 22:18:12 WARN ]     at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
! [Sun 22:18:12 WARN ]     at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
! [Sun 22:18:12 WARN ]     at java.base/java.util.ArrayList.writeObject(ArrayList.java:949)
! [Sun 22:18:12 WARN ]     at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
! [Sun 22:18:12 WARN ]     at java.base/java.lang.reflect.Method.invoke(Method.java:580)
! [Sun 22:18:12 WARN ]     at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1078)
 
! [Sun 22:18:12 WARN ]     at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
! [Sun 22:18:12 WARN ]     at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
! [Sun 22:18:12 WARN ]     at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
! [Sun 22:18:12 WARN ]     at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
! [Sun 22:18:12 WARN ]     at CoreProtect-22.4.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:27)
! [Sun 22:18:12 WARN ]     at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:49)
! [Sun 22:18:12 WARN ]     at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
! [Sun 22:18:12 WARN ]     at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
! [Sun 22:18:12 WARN ]     at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
! [Sun 22:18:12 WARN ]     at java.base/java.lang.Thread.run(Thread.java:1570)
! [Sun 22:18:12 WARN ] java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.next()" because "resultSet" is null
! [Sun 22:18:12 WARN ]     at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:51)
! [Sun 22:18:12 WARN ]     at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
! [Sun 22:18:12 WARN ]     at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
! [Sun 22:18:12 WARN ]     at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
! [Sun 22:18:12 WARN ]     at java.base/java.lang.Thread.run(Thread.java:1570)

**Comment by Skullians** [comment]
Hey, what version of mc is this.
v22.4 doesn't support 1.21+.
If you're running 1.21 or 1.21.1, v23 solves this issue and is available on the **free tier** of Patreon - https://www.patreon.com/posts/113032756

If you are on 1.21.2+, you will either need to compile the plugin yourself or become patreon Tier 1 or higher to access the supported early access builds.

**Comment by Dragsio** [comment]
Try this jar. It's working for me.

[CoreProtect-22.4-fix.jar](https://www.mediafire.com/file/x84m7qqm2qqm8to/CoreProtect-22.4-fix.jar)

**Comment by Skullians** [comment]
Please exercise caution when downloading random jarfiles by the way.

**Comment by DereC4** [comment]
Getting this too

**Comment by forditt** [comment]
Fixed in the newest version from Patreon
