### ISSUE TITLE
java.io.NotSerializableException: org.bukkit.craftbukkit.entity.CraftVillager$CraftProfession

### ISSUE THREAD

**Issue by imlaptev** [PlayPro/CoreProtect#689]
Hey, getting this issue with CoreProtect when villagers die. Not sure what's up, been using CP for years and I haven't had this issue before

[23:25:14 WARN]: java.io.NotSerializableException: org.bukkit.craftbukkit.entity.CraftVillager$CraftProfession
[23:25:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1200)
[23:25:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[23:25:14 WARN]:        at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[23:25:14 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[23:25:14 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[23:25:14 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[23:25:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[23:25:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[23:25:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[23:25:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[23:25:14 WARN]:        at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[23:25:14 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[23:25:14 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[23:25:14 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[23:25:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[23:25:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[23:25:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[23:25:14 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[23:25:14 WARN]:        at CoreProtect-22.4 (1).jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:27)
[23:25:14 WARN]:        at CoreProtect-22.4 (1).jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:49)
[23:25:14 WARN]:        at CoreProtect-22.4 (1).jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[23:25:14 WARN]:        at CoreProtect-22.4 (1).jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[23:25:14 WARN]:        at CoreProtect-22.4 (1).jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[23:25:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by MajliTech** [comment]
```
java.io.NotSerializableException: org.bukkit.craftbukkit.entity.CraftCat$CraftType
```
issue exists

**Comment by MajliTech** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
> 

but the problem still persists
