### ISSUE TITLE
Folia 1.21.4 with MySQL Error

### ISSUE THREAD

**Issue by Panda260** [PlayPro/CoreProtect#692]
hey I always get this error in the console, it's really spammed. I use the latest Folia Dev version 1.21.4 and CoreProtect with MySQL. Without mysql the error doesn't appear

https://haste.simplecloud.app/mizevakaho.md

[03:08:52 WARN]: java.io.NotSerializableException: org.bukkit.craftbukkit.attribute.CraftAttribute
[03:08:52 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1200)
[03:08:52 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[03:08:52 WARN]:        at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[03:08:52 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[03:08:52 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[03:08:52 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[03:08:52 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[03:08:52 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[03:08:52 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[03:08:52 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[03:08:52 WARN]:        at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[03:08:52 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[03:08:52 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[03:08:52 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[03:08:52 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[03:08:52 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[03:08:52 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[03:08:52 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[03:08:52 WARN]:        at java.base/java.util.ArrayList.writeObject(ArrayList.java:948)
[03:08:52 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[03:08:52 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[03:08:52 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1072)
[03:08:52 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[03:08:52 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1451)
[03:08:52 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
[03:08:52 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
[03:08:52 WARN]:        at CoreProtect-22.4 (1).jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:27)
[03:08:52 WARN]:        at CoreProtect-22.4 (1).jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:49)
[03:08:52 WARN]:        at CoreProtect-22.4 (1).jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[03:08:52 WARN]:        at CoreProtect-22.4 (1).jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[03:08:52 WARN]:        at CoreProtect-22.4 (1).jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[03:08:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[03:08:52 WARN]: java.sql.SQLException: Illegal operation on empty result set.
[03:08:52 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
[03:08:52 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[03:08:52 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:81)
[03:08:52 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:55)
[03:08:52 WARN]:        at com.mysql.cj.jdbc.result.ResultSetImpl.checkRowPos(ResultSetImpl.java:541)
[03:08:52 WARN]:        at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1304)
[03:08:52 WARN]:        at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:852)
[03:08:52 WARN]:        at CoreProtect-22.4 (1).jar//net.coreprotect.hikari.pool.HikariProxyResultSet.getInt(HikariProxyResultSet.java)
[03:08:52 WARN]:        at CoreProtect-22.4 (1).jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:58)
[03:08:52 WARN]:        at CoreProtect-22.4 (1).jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[03:08:52 WARN]:        at CoreProtect-22.4 (1).jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[03:08:52 WARN]:        at CoreProtect-22.4 (1).jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[03:08:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Panda260** [comment]
was fixed in the latest build
