### ISSUE TITLE
Console spam on player death event

### ISSUE THREAD

**Issue by HC-Emro** [PlayPro/CoreProtect#71]
Console spam on player death event (Paper 1.16.5)

![image](https://user-images.githubusercontent.com/56135028/130332056-daa4ab61-023e-44a5-80ff-b0ab451b184b.png)

```
>.... [20:48:40 ERROR]: Could not pass event PlayerDeathEvent to CoreProtect v20.1
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.clone()" because "itemStack" is null
at net.coreprotect.listener.player.PlayerDropItemListener.playerDropItem(PlayerDropItemListener.java:27) ~[?:?]
at net.coreprotect.listener.player.PlayerDeathListener.onPlayerDeath(PlayerDeathListener.java:42) ~[?:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Paper-785]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-785]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-785]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-785]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:876) ~[patched_1.16.5.jar:git-Paper-785]
at net.minecraft.server.v1_16_R3.EntityPlayer.die(EntityPlayer.java:818) ~[patched_1.16.5.jar:git-Paper-785]
at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1362) ~[patched_1.16.5.jar:git-Paper-785]
at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:870) ~[patched_1.16.5.jar:git-Paper-785]
at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:982) ~[patched_1.16.5.jar:git-Paper-785]
at net.minecraft.server.v1_16_R3.EntitySnowball.a(SourceFile:58) ~[patched_1.16.5.jar:git-Paper-785]
at net.minecraft.server.v1_16_R3.IProjectile.a(IProjectile.java:150) ~[patched_1.16.5.jar:git-Paper-785]
at net.minecraft.server.v1_16_R3.EntitySnowball.a(SourceFile:63) ~[patched_1.16.5.jar:git-Paper-785]
at net.minecraft.server.v1_16_R3.IProjectile.preOnHit(IProjectile.java:141) ~[patched_1.16.5.jar:git-Paper-785]
at net.minecraft.server.v1_16_R3.EntityProjectile.tick(EntityProjectile.java:70) ~[patched_1.16.5.jar:git-Paper-785]
at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:960) ~[patched_1.16.5.jar:git-Paper-785]
at net.minecraft.server.v1_16_R3.World.a(World.java:955) ~[patched_1.16.5.jar:git-Paper-785]
at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:646) ~[patched_1.16.5.jar:git-Paper-785]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1490) ~[patched_1.16.5.jar:git-Paper-785]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-785]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-785]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-785]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-785]
at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Intelli** [comment]
Fix will be included in CoreProtect v20.2.

Note that this is unreplicable on a clean install with no other plugins. It's likely being caused by another plugin modifying items dropped upon player deaths.
