### ISSUE TITLE
Get an error suddenly 

### ISSUE THREAD

**Issue by WongIong** [PlayPro/CoreProtect#78]
[07:06:29 INFO]: [CoreProtect] 無法連線到 MySQL 伺服器。   <=Unable to connect to MYSQL server
[07:06:29 WARN]: java.sql.SQLNonTransientConnectionException: Too many connections
[07:06:29 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
[07:06:29 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[07:06:29 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833)
[07:06:29 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)
[07:06:29 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
[07:06:29 WARN]:        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[07:06:29 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
[07:06:29 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
[07:06:29 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.database.Database.getConnection(Database.java:143)
[07:06:29 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.database.Database.getConnection(Database.java:130)
[07:06:29 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.consumer.process.Process.validateConnection(Process.java:69)
[07:06:29 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:95)
[07:06:29 WARN]:        at CoreProtect-20.1.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:141)
[07:06:29 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Intelli** [comment]
Please see https://www.thegeekdiary.com/mysql-error-too-many-connections-and-how-to-resolve-it/
