### ISSUE TITLE
Could not pass event PlayerArmorStandManipulateEvent to CoreProtect v2.15.1

### ISSUE THREAD

**Issue by marvinej** [PlayPro/CoreProtect#8]
[Mon, 8. Oct 2018 10:32:07 EDT INFO] This server is running CraftBukkit version git-Spigot-f6a273b-8ab46ff (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

[03:49:42] [Server thread/ERROR]: Could not pass event PlayerArmorStandManipulateEvent to CoreProtect v2.15.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.EntityArmorStand.a(EntityArmorStand.java:385) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.EntityArmorStand.a(EntityArmorStand.java:322) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1861) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:69) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockState.setType(CraftBlockState.java:125) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.coreprotect.consumer.Queue.queueContainerTransaction(Queue.java:136) ~[?:?]
	at net.coreprotect.listener.PlayerListener.onPlayerArmorStandManipulateEvent(PlayerListener.java:279) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	... 17 more
[03:49:42] [Server thread/ERROR]: Could not pass event PlayerArmorStandManipulateEvent to CoreProtect v2.15.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.EntityArmorStand.a(EntityArmorStand.java:385) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.EntityArmorStand.a(EntityArmorStand.java:333) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1861) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:69) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockState.setType(CraftBlockState.java:125) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.coreprotect.consumer.Queue.queueContainerTransaction(Queue.java:136) ~[?:?]
	at net.coreprotect.listener.PlayerListener.onPlayerArmorStandManipulateEvent(PlayerListener.java:279) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	... 17 more

**Comment by KarlOfDuty** [comment]
I can confirm the issue also exists in 1.13.2.

**Comment by SirGoldman-git** [comment]
I can also confirm this issue on 1.13.2 https://pastebin.com/wzsBDSjY
